/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_app (void);
GtkWidget* create_about (void);
GtkWidget* create_messagebox1 (void);
GtkWidget* create_messagebox2 (void);
GtkWidget* create_box_filename_needed (void);
GtkWidget* create_box_debugexe_needed (void);
