/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

static GnomeUIInfo file1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_EXIT_ITEM (on_exit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Generate Bookmarks"),
    NULL,
    on_generate_bookmarks1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_EXEC,
    0, 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file1_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (edit1_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (help1_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_app (void)
{
  GtkWidget *app;
  GtkWidget *dock1;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button_reset;
  GtkWidget *button_resume;
  GtkWidget *button_halt;
  GtkWidget *button_step;
  GtkWidget *button_resume_with_server;
  GtkWidget *button_exit;
  GtkWidget *hbox1;
  GtkWidget *vbox1;
  GtkWidget *notebook;
  GtkWidget *vbox2;
  GtkWidget *scrolledwindow1;
  GtkWidget *log;
  GtkWidget *hbuttonbox1;
  guint log_clear_key;
  GtkWidget *log_clear;
  guint log_status_key;
  GtkWidget *log_status;
  guint log_versions_key;
  GtkWidget *log_versions;
  GtkWidget *label32;
  GtkWidget *vbox4;
  GtkWidget *scrolledwindow3;
  GtkWidget *bookmark_clist;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *frame_bookmarks;
  GtkWidget *vbox5;
  GtkWidget *hbox4;
  GtkWidget *label37;
  GtkWidget *entry_comment;
  GtkWidget *bookmark_buttons;
  guint bookmark_add_key;
  GtkWidget *bookmark_add;
  guint bookmark_remove_key;
  GtkWidget *bookmark_remove;
  guint bookmark_save_key;
  GtkWidget *bookmark_save;
  guint bookmark_load_key;
  GtkWidget *bookmark_load;
  guint bookmark_clear_key;
  GtkWidget *bookmark_clear;
  GtkWidget *label33;
  GtkWidget *vbox6;
  GtkWidget *table6;
  GtkWidget *fileentry1;
  GtkWidget *exe_entry;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label40;
  GtkWidget *frame24;
  GtkWidget *exe_stack;
  GtkWidget *frame25;
  GtkWidget *exe_task;
  GtkWidget *frame26;
  GtkWidget *exe_event;
  GtkWidget *device_entry;
  GtkWidget *command_entry;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *toggle_reset;
  GtkWidget *label46;
  GtkWidget *fileentry2;
  GtkWidget *directory_entry;
  GtkWidget *toggle_break;
  GtkWidget *toggle_usestack;
  GtkWidget *toggle_usedir;
  GtkWidget *fileentry3;
  GtkWidget *debug_exe_entry;
  GtkWidget *label48;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox2;
  guint exe_run_key;
  GtkWidget *exe_run;
  guint exe_info_key;
  GtkWidget *exe_info;
  guint exe_save_key;
  GtkWidget *exe_save;
  guint exe_load_key;
  GtkWidget *exe_load;
  GtkWidget *label34;
  GtkWidget *vbox7;
  GtkWidget *frame27;
  GtkWidget *table8;
  GtkWidget *cfg_open_editor;
  GtkWidget *cfg_addr2line;
  GtkWidget *cfg_getsymbols;
  GtkWidget *label54;
  GtkWidget *label53;
  GtkWidget *label50;
  GtkWidget *frame28;
  GtkWidget *table9;
  GtkWidget *cfg_fullmem;
  GtkWidget *cfg_status;
  GtkWidget *cfg_version;
  GtkWidget *cfg_pid;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *cfg_device;
  GtkWidget *label63;
  GtkWidget *label47;
  GtkWidget *frame_memory;
  GtkWidget *table7;
  GtkWidget *frame12;
  GtkWidget *edit_addr;
  GtkWidget *frame13;
  GtkWidget *edit_value;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *hbox6;
  GtkWidget *frame_goto;
  GtkWidget *table2;
  GtkWidget *frame8;
  GtkWidget *pc;
  GtkWidget *label7;
  GtkWidget *frame_jump;
  GtkWidget *table5;
  GtkWidget *frame23;
  GtkWidget *jumpaddress;
  GtkWidget *label39;
  GtkWidget *frame_search;
  GtkWidget *table1;
  GtkWidget *search_entry;
  GtkWidget *label5;
  GtkWidget *frame6;
  GtkWidget *hbox2;
  GtkWidget *search_from;
  GtkWidget *label6;
  GtkWidget *search_to;
  GtkWidget *load_memory;
  GtkWidget *label13;
  GtkWidget *hbox5;
  GtkWidget *frame15;
  GtkWidget *findhex;
  GtkWidget *label38;
  GtkWidget *frame_mask;
  GtkWidget *mask;
  GtkWidget *frame_registers;
  GtkWidget *registers;
  GtkWidget *vpaned1;
  GtkWidget *frame_disasm;
  GtkWidget *disassembly;
  GtkWidget *vpaned2;
  GtkWidget *frame_breakpoints;
  GtkWidget *vbox3;
  GtkWidget *scrolledwindow2;
  GtkWidget *bkpt_clist;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *hbox3;
  GtkWidget *toolbar3;
  GtkWidget *bkpt_add;
  GtkWidget *bkpt_remove;
  GtkWidget *bkpt_enable;
  GtkWidget *bkpt_hardware;
  GtkWidget *frame_masks;
  GtkWidget *table4;
  GtkWidget *frame18;
  GtkWidget *data_mask;
  GtkWidget *frame19;
  GtkWidget *data_addr;
  GtkWidget *frame20;
  GtkWidget *pc_mask;
  GtkWidget *frame21;
  GtkWidget *pc_addr;
  GtkWidget *label31;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label28;
  GtkWidget *frame_results;
  GtkWidget *search_scrolledwindow;
  GtkWidget *search_clist;
  GtkWidget *label9;
  GtkWidget *valueofshit;
  GtkWidget *label10;
  GtkWidget *appbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  app = gnome_app_new ("Debug", _("PSXDEV Debugger"));
  gtk_object_set_data (GTK_OBJECT (app), "app", app);

  dock1 = GNOME_APP (app)->dock;
  gtk_widget_ref (dock1);
  gtk_object_set_data_full (GTK_OBJECT (app), "dock1", dock1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dock1);

  gnome_app_create_menus (GNOME_APP (app), menubar1_uiinfo);

  gtk_widget_ref (menubar1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "file1",
                            menubar1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "exit1",
                            file1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "edit1",
                            menubar1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "generate_bookmarks1",
                            edit1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "help1",
                            menubar1_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "about1",
                            help1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (app), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gnome_app_add_toolbar (GNOME_APP (app), GTK_TOOLBAR (toolbar1), "toolbar1",
                                GNOME_DOCK_ITEM_BEH_EXCLUSIVE,
                                GNOME_DOCK_TOP, 1, 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 1);
  gtk_toolbar_set_space_size (GTK_TOOLBAR (toolbar1), 16);
  gtk_toolbar_set_space_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_SPACE_LINE);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar1), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_REFRESH);
  button_reset = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Reset"),
                                _("Reset the PlayStation"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button_reset);
  gtk_object_set_data_full (GTK_OBJECT (app), "button_reset", button_reset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_reset);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_TIMER);
  button_resume = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Resume"),
                                _("Resume operation on PlayStation and give control back to it"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button_resume);
  gtk_object_set_data_full (GTK_OBJECT (app), "button_resume", button_resume,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_resume);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_TIMER_STOP);
  button_halt = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Halt"),
                                _("Stop execution on PlayStation and take over control"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button_halt);
  gtk_object_set_data_full (GTK_OBJECT (app), "button_halt", button_halt,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_halt);
  gtk_widget_add_accelerator (button_halt, "clicked", accel_group,
                              GDK_Break, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_FORWARD);
  button_step = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Step"),
                                _("Perform a single step"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button_step);
  gtk_object_set_data_full (GTK_OBJECT (app), "button_step", button_step,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_step);
  gtk_widget_add_accelerator (button_step, "clicked", accel_group,
                              GDK_F5, 0,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_EXEC);
  button_resume_with_server = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Server"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button_resume_with_server);
  gtk_object_set_data_full (GTK_OBJECT (app), "button_resume_with_server", button_resume_with_server,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_resume_with_server);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_EXIT);
  button_exit = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Exit"),
                                _("Quit this fine application"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button_exit);
  gtk_object_set_data_full (GTK_OBJECT (app), "button_exit", button_exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_exit);

  hbox1 = gtk_hbox_new (FALSE, 8);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (app), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gnome_app_set_contents (GNOME_APP (app), hbox1);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 8);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (app), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox1, FALSE, TRUE, 0);

  notebook = gtk_notebook_new ();
  gtk_widget_ref (notebook);
  gtk_object_set_data_full (GTK_OBJECT (app), "notebook", notebook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook, TRUE, TRUE, 0);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook), TRUE);
  gtk_notebook_popup_enable (GTK_NOTEBOOK (notebook));

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (app), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook), vbox2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (app), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  log = gtk_text_new (NULL, NULL);
  gtk_widget_ref (log);
  gtk_object_set_data_full (GTK_OBJECT (app), "log", log,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), log);
  gtk_text_set_editable (GTK_TEXT (log), TRUE);
  gtk_widget_realize (log);
  gtk_text_insert (GTK_TEXT (log), NULL, NULL, NULL,
                   _("Welcome to PSXDEBUG!\nThis is a design prototype.\n"), 49);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (app), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox1), 0, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox1), 0, 0);

  log_clear = gtk_button_new_with_label ("");
  log_clear_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (log_clear)->child),
                                   _("_Clear"));
  gtk_widget_add_accelerator (log_clear, "clicked", accel_group,
                              log_clear_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (log_clear);
  gtk_object_set_data_full (GTK_OBJECT (app), "log_clear", log_clear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_clear);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), log_clear);
  GTK_WIDGET_SET_FLAGS (log_clear, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, log_clear, _("Clear all messages"), NULL);

  log_status = gtk_button_new_with_label ("");
  log_status_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (log_status)->child),
                                   _("_Status"));
  gtk_widget_add_accelerator (log_status, "clicked", accel_group,
                              log_status_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (log_status);
  gtk_object_set_data_full (GTK_OBJECT (app), "log_status", log_status,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_status);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), log_status);
  GTK_WIDGET_SET_FLAGS (log_status, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, log_status, _("Get status of remote target connection link"), NULL);

  log_versions = gtk_button_new_with_label ("");
  log_versions_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (log_versions)->child),
                                   _("_Versions"));
  gtk_widget_add_accelerator (log_versions, "clicked", accel_group,
                              log_versions_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (log_versions);
  gtk_object_set_data_full (GTK_OBJECT (app), "log_versions", log_versions,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_versions);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), log_versions);
  GTK_WIDGET_SET_FLAGS (log_versions, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, log_versions, _("Get versions of caetla sub systems"), NULL);

  label32 = gtk_label_new (_("Messages"));
  gtk_widget_ref (label32);
  gtk_object_set_data_full (GTK_OBJECT (app), "label32", label32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label32);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (app), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook), vbox4);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (app), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  bookmark_clist = gtk_clist_new (2);
  gtk_widget_ref (bookmark_clist);
  gtk_object_set_data_full (GTK_OBJECT (app), "bookmark_clist", bookmark_clist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bookmark_clist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), bookmark_clist);
  gtk_clist_set_column_width (GTK_CLIST (bookmark_clist), 0, 76);
  gtk_clist_set_column_width (GTK_CLIST (bookmark_clist), 1, 80);
  gtk_clist_column_titles_show (GTK_CLIST (bookmark_clist));

  label35 = gtk_label_new (_("Address"));
  gtk_widget_ref (label35);
  gtk_object_set_data_full (GTK_OBJECT (app), "label35", label35,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label35);
  gtk_clist_set_column_widget (GTK_CLIST (bookmark_clist), 0, label35);
  gtk_misc_set_alignment (GTK_MISC (label35), 7.45058e-09, 0.5);

  label36 = gtk_label_new (_("Comment"));
  gtk_widget_ref (label36);
  gtk_object_set_data_full (GTK_OBJECT (app), "label36", label36,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label36);
  gtk_clist_set_column_widget (GTK_CLIST (bookmark_clist), 1, label36);
  gtk_misc_set_alignment (GTK_MISC (label36), 7.45058e-09, 0.5);

  frame_bookmarks = gtk_frame_new (NULL);
  gtk_widget_ref (frame_bookmarks);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_bookmarks", frame_bookmarks,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_bookmarks);
  gtk_box_pack_start (GTK_BOX (vbox4), frame_bookmarks, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_bookmarks), GTK_SHADOW_NONE);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (app), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (frame_bookmarks), vbox5);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (app), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox4, FALSE, TRUE, 0);

  label37 = gtk_label_new (_("Comment"));
  gtk_widget_ref (label37);
  gtk_object_set_data_full (GTK_OBJECT (app), "label37", label37,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox4), label37, FALSE, FALSE, 0);

  entry_comment = gtk_entry_new ();
  gtk_widget_ref (entry_comment);
  gtk_object_set_data_full (GTK_OBJECT (app), "entry_comment", entry_comment,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_comment);
  gtk_box_pack_start (GTK_BOX (hbox4), entry_comment, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, entry_comment, _("You can use these comments like assembler labels for addresses"), NULL);

  bookmark_buttons = gtk_hbutton_box_new ();
  gtk_widget_ref (bookmark_buttons);
  gtk_object_set_data_full (GTK_OBJECT (app), "bookmark_buttons", bookmark_buttons,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bookmark_buttons);
  gtk_box_pack_start (GTK_BOX (vbox5), bookmark_buttons, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (bookmark_buttons), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (bookmark_buttons), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (bookmark_buttons), 0, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (bookmark_buttons), 0, 0);

  bookmark_add = gtk_button_new_with_label ("");
  bookmark_add_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (bookmark_add)->child),
                                   _("_Add"));
  gtk_widget_add_accelerator (bookmark_add, "clicked", accel_group,
                              bookmark_add_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (bookmark_add);
  gtk_object_set_data_full (GTK_OBJECT (app), "bookmark_add", bookmark_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bookmark_add);
  gtk_container_add (GTK_CONTAINER (bookmark_buttons), bookmark_add);
  GTK_WIDGET_SET_FLAGS (bookmark_add, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bookmark_add, _("Add new entry with current display address and current comment"), NULL);

  bookmark_remove = gtk_button_new_with_label ("");
  bookmark_remove_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (bookmark_remove)->child),
                                   _("_Remove"));
  gtk_widget_add_accelerator (bookmark_remove, "clicked", accel_group,
                              bookmark_remove_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (bookmark_remove);
  gtk_object_set_data_full (GTK_OBJECT (app), "bookmark_remove", bookmark_remove,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bookmark_remove);
  gtk_container_add (GTK_CONTAINER (bookmark_buttons), bookmark_remove);
  GTK_WIDGET_SET_FLAGS (bookmark_remove, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bookmark_remove, _("Remove selected entry"), NULL);

  bookmark_save = gtk_button_new_with_label ("");
  bookmark_save_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (bookmark_save)->child),
                                   _("_Save"));
  gtk_widget_add_accelerator (bookmark_save, "clicked", accel_group,
                              bookmark_save_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (bookmark_save);
  gtk_object_set_data_full (GTK_OBJECT (app), "bookmark_save", bookmark_save,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bookmark_save);
  gtk_container_add (GTK_CONTAINER (bookmark_buttons), bookmark_save);
  GTK_WIDGET_SET_FLAGS (bookmark_save, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bookmark_save, _("Save to $HOME/.psxdev/debug_bookmarks"), NULL);

  bookmark_load = gtk_button_new_with_label ("");
  bookmark_load_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (bookmark_load)->child),
                                   _("_Load"));
  gtk_widget_add_accelerator (bookmark_load, "clicked", accel_group,
                              bookmark_load_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (bookmark_load);
  gtk_object_set_data_full (GTK_OBJECT (app), "bookmark_load", bookmark_load,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bookmark_load);
  gtk_container_add (GTK_CONTAINER (bookmark_buttons), bookmark_load);
  GTK_WIDGET_SET_FLAGS (bookmark_load, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bookmark_load, _("Load from $HOME/.psxdev/debug_bookmarks"), NULL);

  bookmark_clear = gtk_button_new_with_label ("");
  bookmark_clear_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (bookmark_clear)->child),
                                   _("_Clear"));
  gtk_widget_add_accelerator (bookmark_clear, "clicked", accel_group,
                              bookmark_clear_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (bookmark_clear);
  gtk_object_set_data_full (GTK_OBJECT (app), "bookmark_clear", bookmark_clear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bookmark_clear);
  gtk_container_add (GTK_CONTAINER (bookmark_buttons), bookmark_clear);
  GTK_WIDGET_SET_FLAGS (bookmark_clear, GTK_CAN_DEFAULT);

  label33 = gtk_label_new (_("Bookmarks"));
  gtk_widget_ref (label33);
  gtk_object_set_data_full (GTK_OBJECT (app), "label33", label33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label33);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label33);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (app), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (notebook), vbox6);

  table6 = gtk_table_new (13, 2, FALSE);
  gtk_widget_ref (table6);
  gtk_object_set_data_full (GTK_OBJECT (app), "table6", table6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table6);
  gtk_box_pack_start (GTK_BOX (vbox6), table6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table6), 8);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 2);

  fileentry1 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_ref (fileentry1);
  gtk_object_set_data_full (GTK_OBJECT (app), "fileentry1", fileentry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fileentry1);
  gtk_table_attach (GTK_TABLE (table6), fileentry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  exe_entry = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry1));
  gtk_widget_ref (exe_entry);
  gtk_object_set_data_full (GTK_OBJECT (app), "exe_entry", exe_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exe_entry);

  label41 = gtk_label_new (_("Stack"));
  gtk_widget_ref (label41);
  gtk_object_set_data_full (GTK_OBJECT (app), "label41", label41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table6), label41, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  label42 = gtk_label_new (_("Task"));
  gtk_widget_ref (label42);
  gtk_object_set_data_full (GTK_OBJECT (app), "label42", label42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table6), label42, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label42), 0, 0.5);

  label43 = gtk_label_new (_("Event"));
  gtk_widget_ref (label43);
  gtk_object_set_data_full (GTK_OBJECT (app), "label43", label43,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table6), label43, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  label40 = gtk_label_new (_("Executable"));
  gtk_widget_ref (label40);
  gtk_object_set_data_full (GTK_OBJECT (app), "label40", label40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table6), label40, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  frame24 = gtk_frame_new (NULL);
  gtk_widget_ref (frame24);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame24", frame24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame24);
  gtk_table_attach (GTK_TABLE (table6), frame24, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame24), GTK_SHADOW_IN);

  exe_stack = create_hexentry ("exe_stack", NULL, NULL, -2147352592, 0);
  gtk_widget_ref (exe_stack);
  gtk_object_set_data_full (GTK_OBJECT (app), "exe_stack", exe_stack,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exe_stack);
  gtk_container_add (GTK_CONTAINER (frame24), exe_stack);
  GTK_WIDGET_SET_FLAGS (exe_stack, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (exe_stack, GTK_CAN_DEFAULT);

  frame25 = gtk_frame_new (NULL);
  gtk_widget_ref (frame25);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame25", frame25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame25);
  gtk_table_attach (GTK_TABLE (table6), frame25, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame25), GTK_SHADOW_IN);

  exe_task = create_hexentry ("exe_task", NULL, NULL, 4, 0);
  gtk_widget_ref (exe_task);
  gtk_object_set_data_full (GTK_OBJECT (app), "exe_task", exe_task,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exe_task);
  gtk_container_add (GTK_CONTAINER (frame25), exe_task);
  GTK_WIDGET_SET_FLAGS (exe_task, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (exe_task, GTK_CAN_DEFAULT);

  frame26 = gtk_frame_new (NULL);
  gtk_widget_ref (frame26);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame26", frame26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame26);
  gtk_table_attach (GTK_TABLE (table6), frame26, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame26), GTK_SHADOW_IN);

  exe_event = create_hexentry ("exe_event", NULL, NULL, 16, 0);
  gtk_widget_ref (exe_event);
  gtk_object_set_data_full (GTK_OBJECT (app), "exe_event", exe_event,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exe_event);
  gtk_container_add (GTK_CONTAINER (frame26), exe_event);
  GTK_WIDGET_SET_FLAGS (exe_event, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (exe_event, GTK_CAN_DEFAULT);

  device_entry = gtk_entry_new ();
  gtk_widget_ref (device_entry);
  gtk_object_set_data_full (GTK_OBJECT (app), "device_entry", device_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (device_entry);
  gtk_table_attach (GTK_TABLE (table6), device_entry, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (device_entry), _("/dev/pccl"));

  command_entry = gtk_entry_new ();
  gtk_widget_ref (command_entry);
  gtk_object_set_data_full (GTK_OBJECT (app), "command_entry", command_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (command_entry);
  gtk_table_attach (GTK_TABLE (table6), command_entry, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (command_entry), _("psx-run"));

  label44 = gtk_label_new (_("Device"));
  gtk_widget_ref (label44);
  gtk_object_set_data_full (GTK_OBJECT (app), "label44", label44,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table6), label44, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  label45 = gtk_label_new (_("Command"));
  gtk_widget_ref (label45);
  gtk_object_set_data_full (GTK_OBJECT (app), "label45", label45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table6), label45, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  toggle_reset = gtk_check_button_new_with_label (_("Reset before upload ?"));
  gtk_widget_ref (toggle_reset);
  gtk_object_set_data_full (GTK_OBJECT (app), "toggle_reset", toggle_reset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toggle_reset);
  gtk_table_attach (GTK_TABLE (table6), toggle_reset, 0, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (toggle_reset), TRUE);

  label46 = gtk_label_new (_("Directory"));
  gtk_widget_ref (label46);
  gtk_object_set_data_full (GTK_OBJECT (app), "label46", label46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table6), label46, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 7.45058e-09, 0.5);

  fileentry2 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_ref (fileentry2);
  gtk_object_set_data_full (GTK_OBJECT (app), "fileentry2", fileentry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fileentry2);
  gtk_table_attach (GTK_TABLE (table6), fileentry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_directory (GNOME_FILE_ENTRY (fileentry2), TRUE);

  directory_entry = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry2));
  gtk_widget_ref (directory_entry);
  gtk_object_set_data_full (GTK_OBJECT (app), "directory_entry", directory_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (directory_entry);

  toggle_break = gtk_check_button_new_with_label (_("Break before main() ?"));
  gtk_widget_ref (toggle_break);
  gtk_object_set_data_full (GTK_OBJECT (app), "toggle_break", toggle_break,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toggle_break);
  gtk_table_attach (GTK_TABLE (table6), toggle_break, 0, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  toggle_usestack = gtk_check_button_new_with_label (_("Use stack from executable ?"));
  gtk_widget_ref (toggle_usestack);
  gtk_object_set_data_full (GTK_OBJECT (app), "toggle_usestack", toggle_usestack,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toggle_usestack);
  gtk_table_attach (GTK_TABLE (table6), toggle_usestack, 0, 2, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (toggle_usestack), TRUE);

  toggle_usedir = gtk_check_button_new_with_label (_("Use the directory path from the executable ?"));
  gtk_widget_ref (toggle_usedir);
  gtk_object_set_data_full (GTK_OBJECT (app), "toggle_usedir", toggle_usedir,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toggle_usedir);
  gtk_table_attach (GTK_TABLE (table6), toggle_usedir, 0, 2, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (toggle_usedir), TRUE);

  fileentry3 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_ref (fileentry3);
  gtk_object_set_data_full (GTK_OBJECT (app), "fileentry3", fileentry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fileentry3);
  gtk_table_attach (GTK_TABLE (table6), fileentry3, 1, 2, 12, 13,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  debug_exe_entry = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry3));
  gtk_widget_ref (debug_exe_entry);
  gtk_object_set_data_full (GTK_OBJECT (app), "debug_exe_entry", debug_exe_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (debug_exe_entry);

  label48 = gtk_label_new (_("Debug EXE"));
  gtk_widget_ref (label48);
  gtk_object_set_data_full (GTK_OBJECT (app), "label48", label48,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table6), label48, 0, 1, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 7.45058e-09, 0.5);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (app), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (table6), hseparator1, 0, 2, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 2);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (app), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox6), hbuttonbox2, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox2), 0, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox2), 0, 0);

  exe_run = gtk_button_new_with_label ("");
  exe_run_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exe_run)->child),
                                   _("_Run"));
  gtk_widget_add_accelerator (exe_run, "clicked", accel_group,
                              exe_run_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (exe_run);
  gtk_object_set_data_full (GTK_OBJECT (app), "exe_run", exe_run,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exe_run);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), exe_run);
  GTK_WIDGET_SET_FLAGS (exe_run, GTK_CAN_DEFAULT);

  exe_info = gtk_button_new_with_label ("");
  exe_info_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exe_info)->child),
                                   _("_Info"));
  gtk_widget_add_accelerator (exe_info, "clicked", accel_group,
                              exe_info_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (exe_info);
  gtk_object_set_data_full (GTK_OBJECT (app), "exe_info", exe_info,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exe_info);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), exe_info);
  GTK_WIDGET_SET_FLAGS (exe_info, GTK_CAN_DEFAULT);

  exe_save = gtk_button_new_with_label ("");
  exe_save_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exe_save)->child),
                                   _("_Save"));
  gtk_widget_add_accelerator (exe_save, "clicked", accel_group,
                              exe_save_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (exe_save);
  gtk_object_set_data_full (GTK_OBJECT (app), "exe_save", exe_save,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exe_save);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), exe_save);
  GTK_WIDGET_SET_FLAGS (exe_save, GTK_CAN_DEFAULT);

  exe_load = gtk_button_new_with_label ("");
  exe_load_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exe_load)->child),
                                   _("_Load"));
  gtk_widget_add_accelerator (exe_load, "clicked", accel_group,
                              exe_load_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (exe_load);
  gtk_object_set_data_full (GTK_OBJECT (app), "exe_load", exe_load,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exe_load);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), exe_load);
  GTK_WIDGET_SET_FLAGS (exe_load, GTK_CAN_DEFAULT);

  label34 = gtk_label_new (_("Upload"));
  gtk_widget_ref (label34);
  gtk_object_set_data_full (GTK_OBJECT (app), "label34", label34,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 2), label34);

  vbox7 = gtk_vbox_new (FALSE, 4);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (app), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (notebook), vbox7);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 4);

  frame27 = gtk_frame_new (_("Templates"));
  gtk_widget_ref (frame27);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame27", frame27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame27);
  gtk_box_pack_start (GTK_BOX (vbox7), frame27, FALSE, TRUE, 0);

  table8 = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (table8);
  gtk_object_set_data_full (GTK_OBJECT (app), "table8", table8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (frame27), table8);
  gtk_container_set_border_width (GTK_CONTAINER (table8), 8);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 2);

  cfg_open_editor = gtk_entry_new ();
  gtk_widget_ref (cfg_open_editor);
  gtk_object_set_data_full (GTK_OBJECT (app), "cfg_open_editor", cfg_open_editor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cfg_open_editor);
  gtk_table_attach (GTK_TABLE (table8), cfg_open_editor, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (cfg_open_editor), _("nc -read -line %d -noask %s"));

  cfg_addr2line = gtk_entry_new ();
  gtk_widget_ref (cfg_addr2line);
  gtk_object_set_data_full (GTK_OBJECT (app), "cfg_addr2line", cfg_addr2line,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cfg_addr2line);
  gtk_table_attach (GTK_TABLE (table8), cfg_addr2line, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (cfg_addr2line), _("psx-addr2line -e %s --demangle 0x%08lx"));

  cfg_getsymbols = gtk_entry_new ();
  gtk_widget_ref (cfg_getsymbols);
  gtk_object_set_data_full (GTK_OBJECT (app), "cfg_getsymbols", cfg_getsymbols,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cfg_getsymbols);
  gtk_table_attach (GTK_TABLE (table8), cfg_getsymbols, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (cfg_getsymbols), _("psx-nm %s | grep \" T \" | awk '{print \"0x\" $0}'"));

  label54 = gtk_label_new (_("Open editor"));
  gtk_widget_ref (label54);
  gtk_object_set_data_full (GTK_OBJECT (app), "label54", label54,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table8), label54, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  label53 = gtk_label_new (_("Addr to line"));
  gtk_widget_ref (label53);
  gtk_object_set_data_full (GTK_OBJECT (app), "label53", label53,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table8), label53, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);

  label50 = gtk_label_new (_("Get Symbols"));
  gtk_widget_ref (label50);
  gtk_object_set_data_full (GTK_OBJECT (app), "label50", label50,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table8), label50, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);

  frame28 = gtk_frame_new (_("PSXDEV PCCL Communication Link"));
  gtk_widget_ref (frame28);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame28", frame28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame28);
  gtk_box_pack_start (GTK_BOX (vbox7), frame28, FALSE, FALSE, 0);

  table9 = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (table9);
  gtk_object_set_data_full (GTK_OBJECT (app), "table9", table9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table9);
  gtk_container_add (GTK_CONTAINER (frame28), table9);
  gtk_container_set_border_width (GTK_CONTAINER (table9), 8);
  gtk_table_set_row_spacings (GTK_TABLE (table9), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table9), 2);

  cfg_fullmem = gtk_entry_new ();
  gtk_widget_ref (cfg_fullmem);
  gtk_object_set_data_full (GTK_OBJECT (app), "cfg_fullmem", cfg_fullmem,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cfg_fullmem);
  gtk_table_attach (GTK_TABLE (table9), cfg_fullmem, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (cfg_fullmem), _("/proc/pccl/0/fullmem"));

  cfg_status = gtk_entry_new ();
  gtk_widget_ref (cfg_status);
  gtk_object_set_data_full (GTK_OBJECT (app), "cfg_status", cfg_status,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cfg_status);
  gtk_table_attach (GTK_TABLE (table9), cfg_status, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (cfg_status), _("/proc/pccl/0/status"));

  cfg_version = gtk_entry_new ();
  gtk_widget_ref (cfg_version);
  gtk_object_set_data_full (GTK_OBJECT (app), "cfg_version", cfg_version,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cfg_version);
  gtk_table_attach (GTK_TABLE (table9), cfg_version, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (cfg_version), _("/proc/pccl/0/version"));

  cfg_pid = gtk_entry_new ();
  gtk_widget_ref (cfg_pid);
  gtk_object_set_data_full (GTK_OBJECT (app), "cfg_pid", cfg_pid,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cfg_pid);
  gtk_table_attach (GTK_TABLE (table9), cfg_pid, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (cfg_pid), _("/proc/pccl/0/pid"));

  label59 = gtk_label_new (_("Fullmem"));
  gtk_widget_ref (label59);
  gtk_object_set_data_full (GTK_OBJECT (app), "label59", label59,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label59);
  gtk_table_attach (GTK_TABLE (table9), label59, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label59), 0, 0.5);

  label60 = gtk_label_new (_("Status"));
  gtk_widget_ref (label60);
  gtk_object_set_data_full (GTK_OBJECT (app), "label60", label60,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label60);
  gtk_table_attach (GTK_TABLE (table9), label60, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label60), 0, 0.5);

  label61 = gtk_label_new (_("Version"));
  gtk_widget_ref (label61);
  gtk_object_set_data_full (GTK_OBJECT (app), "label61", label61,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table9), label61, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label61), 0, 0.5);

  label62 = gtk_label_new (_("PID"));
  gtk_widget_ref (label62);
  gtk_object_set_data_full (GTK_OBJECT (app), "label62", label62,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table9), label62, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label62), 0, 0.5);

  cfg_device = gtk_entry_new ();
  gtk_widget_ref (cfg_device);
  gtk_object_set_data_full (GTK_OBJECT (app), "cfg_device", cfg_device,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cfg_device);
  gtk_table_attach (GTK_TABLE (table9), cfg_device, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (cfg_device), _("/dev/pccl"));

  label63 = gtk_label_new (_("Device"));
  gtk_widget_ref (label63);
  gtk_object_set_data_full (GTK_OBJECT (app), "label63", label63,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table9), label63, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label63), 0, 0.5);

  label47 = gtk_label_new (_("Configuration"));
  gtk_widget_ref (label47);
  gtk_object_set_data_full (GTK_OBJECT (app), "label47", label47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 3), label47);

  frame_memory = gtk_frame_new (_("Edit Memory"));
  gtk_widget_ref (frame_memory);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_memory", frame_memory,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_memory);
  gtk_box_pack_start (GTK_BOX (vbox1), frame_memory, FALSE, TRUE, 0);

  table7 = gtk_table_new (1, 4, FALSE);
  gtk_widget_ref (table7);
  gtk_object_set_data_full (GTK_OBJECT (app), "table7", table7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table7);
  gtk_container_add (GTK_CONTAINER (frame_memory), table7);
  gtk_container_set_border_width (GTK_CONTAINER (table7), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table7), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table7), 2);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_ref (frame12);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame12", frame12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame12);
  gtk_table_attach (GTK_TABLE (table7), frame12, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame12), GTK_SHADOW_IN);

  edit_addr = create_edit_addr ("edit_addr", NULL, NULL, 0, 0);
  gtk_widget_ref (edit_addr);
  gtk_object_set_data_full (GTK_OBJECT (app), "edit_addr", edit_addr,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_addr);
  gtk_container_add (GTK_CONTAINER (frame12), edit_addr);
  GTK_WIDGET_SET_FLAGS (edit_addr, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (edit_addr, GTK_CAN_DEFAULT);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_ref (frame13);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame13", frame13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame13);
  gtk_table_attach (GTK_TABLE (table7), frame13, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame13), GTK_SHADOW_IN);

  edit_value = create_edit_value ("edit_value", NULL, NULL, 0, 0);
  gtk_widget_ref (edit_value);
  gtk_object_set_data_full (GTK_OBJECT (app), "edit_value", edit_value,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_value);
  gtk_container_add (GTK_CONTAINER (frame13), edit_value);
  GTK_WIDGET_SET_FLAGS (edit_value, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (edit_value, GTK_CAN_DEFAULT);

  label12 = gtk_label_new (_("Value"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (app), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table7), label12, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 7.45058e-09, 0.5);

  label11 = gtk_label_new (_("Address"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (app), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table7), label11, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 7.45058e-09, 0.5);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (app), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox6, FALSE, TRUE, 0);

  frame_goto = gtk_frame_new (_("Display..."));
  gtk_widget_ref (frame_goto);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_goto", frame_goto,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_goto);
  gtk_box_pack_start (GTK_BOX (hbox6), frame_goto, TRUE, TRUE, 0);

  table2 = gtk_table_new (1, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (app), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (frame_goto), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 2);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_ref (frame8);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame8", frame8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame8);
  gtk_table_attach (GTK_TABLE (table2), frame8, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame8), GTK_SHADOW_IN);

  pc = create_pc ("pc", NULL, NULL, 0, 0);
  gtk_widget_ref (pc);
  gtk_object_set_data_full (GTK_OBJECT (app), "pc", pc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pc);
  gtk_container_add (GTK_CONTAINER (frame8), pc);
  GTK_WIDGET_SET_FLAGS (pc, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (pc, GTK_CAN_DEFAULT);

  label7 = gtk_label_new (_("Address"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (app), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table2), label7, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  frame_jump = gtk_frame_new (_("Jump to..."));
  gtk_widget_ref (frame_jump);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_jump", frame_jump,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_jump);
  gtk_box_pack_start (GTK_BOX (hbox6), frame_jump, TRUE, TRUE, 0);

  table5 = gtk_table_new (1, 2, FALSE);
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (app), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (frame_jump), table5);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 2);

  frame23 = gtk_frame_new (NULL);
  gtk_widget_ref (frame23);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame23", frame23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame23);
  gtk_table_attach (GTK_TABLE (table5), frame23, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame23), GTK_SHADOW_IN);

  jumpaddress = create_hexentry ("jumpaddress", NULL, NULL, 0, 0);
  gtk_widget_ref (jumpaddress);
  gtk_object_set_data_full (GTK_OBJECT (app), "jumpaddress", jumpaddress,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (jumpaddress);
  gtk_container_add (GTK_CONTAINER (frame23), jumpaddress);
  GTK_WIDGET_SET_FLAGS (jumpaddress, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (jumpaddress, GTK_CAN_DEFAULT);

  label39 = gtk_label_new (_("Address"));
  gtk_widget_ref (label39);
  gtk_object_set_data_full (GTK_OBJECT (app), "label39", label39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table5), label39, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  frame_search = gtk_frame_new (_("Search Mnemonic Opcode"));
  gtk_widget_ref (frame_search);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_search", frame_search,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_search);
  gtk_box_pack_start (GTK_BOX (vbox1), frame_search, FALSE, TRUE, 0);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (app), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame_search), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);

  search_entry = gtk_entry_new ();
  gtk_widget_ref (search_entry);
  gtk_object_set_data_full (GTK_OBJECT (app), "search_entry", search_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (search_entry);
  gtk_table_attach (GTK_TABLE (table1), search_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (search_entry, FALSE);
  gtk_tooltips_set_tip (tooltips, search_entry, _("Mnemonic substring search"), NULL);

  label5 = gtk_label_new (_("Mnemo"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (app), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 7.45058e-09, 0.5);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_ref (frame6);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame6", frame6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame6);
  gtk_table_attach (GTK_TABLE (table1), frame6, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame6), GTK_SHADOW_IN);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (app), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (frame6), hbox2);

  search_from = create_search_from ("search_from", NULL, NULL, 0, 0);
  gtk_widget_ref (search_from);
  gtk_object_set_data_full (GTK_OBJECT (app), "search_from", search_from,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (search_from);
  gtk_box_pack_start (GTK_BOX (hbox2), search_from, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (search_from, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (search_from, GTK_CAN_DEFAULT);

  label6 = gtk_label_new (_("..."));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (app), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  search_to = create_search_to ("search_to", NULL, NULL, 0, 0);
  gtk_widget_ref (search_to);
  gtk_object_set_data_full (GTK_OBJECT (app), "search_to", search_to,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (search_to);
  gtk_box_pack_start (GTK_BOX (hbox2), search_to, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (search_to, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (search_to, GTK_CAN_DEFAULT);

  load_memory = gtk_button_new_with_label (_("Load"));
  gtk_widget_ref (load_memory);
  gtk_object_set_data_full (GTK_OBJECT (app), "load_memory", load_memory,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load_memory);
  gtk_table_attach (GTK_TABLE (table1), load_memory, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, load_memory, _("Transfer remote memory from selected range into a local buffer for further analysis"), NULL);

  label13 = gtk_label_new (_("Hex"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (app), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 7.45058e-09, 0.5);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (app), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_table_attach (GTK_TABLE (table1), hbox5, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  frame15 = gtk_frame_new (NULL);
  gtk_widget_ref (frame15);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame15", frame15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame15);
  gtk_box_pack_start (GTK_BOX (hbox5), frame15, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame15), GTK_SHADOW_IN);

  findhex = create_findhex ("findhex", NULL, NULL, 0, 0);
  gtk_widget_ref (findhex);
  gtk_object_set_data_full (GTK_OBJECT (app), "findhex", findhex,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (findhex);
  gtk_container_add (GTK_CONTAINER (frame15), findhex);
  gtk_widget_set_sensitive (findhex, FALSE);
  GTK_WIDGET_SET_FLAGS (findhex, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (findhex, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, findhex, _("Search for 32-bit values"), NULL);

  label38 = gtk_label_new (_("Mask"));
  gtk_widget_ref (label38);
  gtk_object_set_data_full (GTK_OBJECT (app), "label38", label38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox5), label38, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 1, 0.5);

  frame_mask = gtk_frame_new (NULL);
  gtk_widget_ref (frame_mask);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_mask", frame_mask,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_mask);
  gtk_box_pack_start (GTK_BOX (hbox5), frame_mask, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_mask), GTK_SHADOW_IN);

  mask = create_hexentry ("mask", NULL, NULL, 0, 0);
  gtk_widget_ref (mask);
  gtk_object_set_data_full (GTK_OBJECT (app), "mask", mask,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mask);
  gtk_container_add (GTK_CONTAINER (frame_mask), mask);
  gtk_widget_set_sensitive (mask, FALSE);
  GTK_WIDGET_SET_FLAGS (mask, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (mask, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, mask, _("Bitmask for 32-bit search"), NULL);

  frame_registers = gtk_frame_new (_("CPU Registers"));
  gtk_widget_ref (frame_registers);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_registers", frame_registers,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_registers);
  gtk_box_pack_start (GTK_BOX (vbox1), frame_registers, FALSE, FALSE, 0);

  registers = create_registers ("registers", NULL, NULL, 0, 0);
  gtk_widget_ref (registers);
  gtk_object_set_data_full (GTK_OBJECT (app), "registers", registers,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (registers);
  gtk_container_add (GTK_CONTAINER (frame_registers), registers);
  GTK_WIDGET_UNSET_FLAGS (registers, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (registers, GTK_CAN_DEFAULT);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (app), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_box_pack_start (GTK_BOX (hbox1), vpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (vpaned1), 300);

  frame_disasm = gtk_frame_new (_("Disassembly"));
  gtk_widget_ref (frame_disasm);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_disasm", frame_disasm,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_disasm);
  gtk_container_add (GTK_CONTAINER (vpaned1), frame_disasm);

  disassembly = create_disassembly ("disassembly", NULL, NULL, 0, 0);
  gtk_widget_ref (disassembly);
  gtk_object_set_data_full (GTK_OBJECT (app), "disassembly", disassembly,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (disassembly);
  gtk_container_add (GTK_CONTAINER (frame_disasm), disassembly);
  GTK_WIDGET_SET_FLAGS (disassembly, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (disassembly, GTK_CAN_DEFAULT);

  vpaned2 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned2);
  gtk_object_set_data_full (GTK_OBJECT (app), "vpaned2", vpaned2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned2);
  gtk_container_add (GTK_CONTAINER (vpaned1), vpaned2);
  gtk_paned_set_position (GTK_PANED (vpaned2), 150);

  frame_breakpoints = gtk_frame_new (_("Breakpoints"));
  gtk_widget_ref (frame_breakpoints);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_breakpoints", frame_breakpoints,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_breakpoints);
  gtk_container_add (GTK_CONTAINER (vpaned2), frame_breakpoints);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (app), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame_breakpoints), vbox3);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (app), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  bkpt_clist = gtk_clist_new (7);
  gtk_widget_ref (bkpt_clist);
  gtk_object_set_data_full (GTK_OBJECT (app), "bkpt_clist", bkpt_clist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bkpt_clist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), bkpt_clist);
  gtk_clist_set_column_width (GTK_CLIST (bkpt_clist), 0, 59);
  gtk_clist_set_column_width (GTK_CLIST (bkpt_clist), 1, 24);
  gtk_clist_set_column_width (GTK_CLIST (bkpt_clist), 2, 90);
  gtk_clist_set_column_width (GTK_CLIST (bkpt_clist), 3, 57);
  gtk_clist_set_column_width (GTK_CLIST (bkpt_clist), 4, 53);
  gtk_clist_set_column_width (GTK_CLIST (bkpt_clist), 5, 54);
  gtk_clist_set_column_width (GTK_CLIST (bkpt_clist), 6, 61);
  gtk_clist_column_titles_show (GTK_CLIST (bkpt_clist));

  label21 = gtk_label_new (_("Address"));
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (app), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_clist_set_column_widget (GTK_CLIST (bkpt_clist), 0, label21);
  gtk_misc_set_alignment (GTK_MISC (label21), 7.45058e-09, 0.5);

  label22 = gtk_label_new (_("Flags"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (app), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_clist_set_column_widget (GTK_CLIST (bkpt_clist), 1, label22);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label23 = gtk_label_new (_("Saved"));
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (app), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_clist_set_column_widget (GTK_CLIST (bkpt_clist), 2, label23);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label24 = gtk_label_new (_("PC ADDR"));
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (app), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_clist_set_column_widget (GTK_CLIST (bkpt_clist), 3, label24);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new (_("PC MASK"));
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (app), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_clist_set_column_widget (GTK_CLIST (bkpt_clist), 4, label25);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new (_("DATA ADDR"));
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (app), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_clist_set_column_widget (GTK_CLIST (bkpt_clist), 5, label26);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("DATA MASK"));
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (app), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_clist_set_column_widget (GTK_CLIST (bkpt_clist), 6, label27);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (app), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, FALSE, FALSE, 0);

  toolbar3 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar3);
  gtk_object_set_data_full (GTK_OBJECT (app), "toolbar3", toolbar3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar3);
  gtk_box_pack_start (GTK_BOX (hbox3), toolbar3, FALSE, FALSE, 0);
  gtk_toolbar_set_space_style (GTK_TOOLBAR (toolbar3), GTK_TOOLBAR_SPACE_LINE);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar3), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_ADD);
  bkpt_add = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Add"),
                                _("Add a new breakpoint"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (bkpt_add);
  gtk_object_set_data_full (GTK_OBJECT (app), "bkpt_add", bkpt_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bkpt_add);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_REMOVE);
  bkpt_remove = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Remove"),
                                _("Remove selected breakpoint"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (bkpt_remove);
  gtk_object_set_data_full (GTK_OBJECT (app), "bkpt_remove", bkpt_remove,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bkpt_remove);
  gtk_widget_set_sensitive (bkpt_remove, FALSE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_INDEX);
  bkpt_enable = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Enable"),
                                _("Enable/Disable selected breakpoint"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (bkpt_enable);
  gtk_object_set_data_full (GTK_OBJECT (app), "bkpt_enable", bkpt_enable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bkpt_enable);
  gtk_widget_set_sensitive (bkpt_enable, FALSE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_EXEC);
  bkpt_hardware = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Hardware"),
                                _("Switch selected breakpoint from software to hardware"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (bkpt_hardware);
  gtk_object_set_data_full (GTK_OBJECT (app), "bkpt_hardware", bkpt_hardware,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bkpt_hardware);
  gtk_widget_set_sensitive (bkpt_hardware, FALSE);

  frame_masks = gtk_frame_new (NULL);
  gtk_widget_ref (frame_masks);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_masks", frame_masks,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_masks);
  gtk_box_pack_start (GTK_BOX (hbox3), frame_masks, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (frame_masks, FALSE);

  table4 = gtk_table_new (2, 4, FALSE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (app), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame_masks), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 4);

  frame18 = gtk_frame_new (NULL);
  gtk_widget_ref (frame18);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame18", frame18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame18);
  gtk_table_attach (GTK_TABLE (table4), frame18, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame18), GTK_SHADOW_IN);

  data_mask = create_hexentry ("data_mask", NULL, NULL, 0, 0);
  gtk_widget_ref (data_mask);
  gtk_object_set_data_full (GTK_OBJECT (app), "data_mask", data_mask,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (data_mask);
  gtk_container_add (GTK_CONTAINER (frame18), data_mask);
  GTK_WIDGET_SET_FLAGS (data_mask, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (data_mask, GTK_CAN_DEFAULT);

  frame19 = gtk_frame_new (NULL);
  gtk_widget_ref (frame19);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame19", frame19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame19);
  gtk_table_attach (GTK_TABLE (table4), frame19, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame19), GTK_SHADOW_IN);

  data_addr = create_hexentry ("data_addr", NULL, NULL, 0, 0);
  gtk_widget_ref (data_addr);
  gtk_object_set_data_full (GTK_OBJECT (app), "data_addr", data_addr,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (data_addr);
  gtk_container_add (GTK_CONTAINER (frame19), data_addr);
  GTK_WIDGET_SET_FLAGS (data_addr, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (data_addr, GTK_CAN_DEFAULT);

  frame20 = gtk_frame_new (NULL);
  gtk_widget_ref (frame20);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame20", frame20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame20);
  gtk_table_attach (GTK_TABLE (table4), frame20, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame20), GTK_SHADOW_IN);

  pc_mask = create_hexentry ("pc_mask", NULL, NULL, 0, 0);
  gtk_widget_ref (pc_mask);
  gtk_object_set_data_full (GTK_OBJECT (app), "pc_mask", pc_mask,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pc_mask);
  gtk_container_add (GTK_CONTAINER (frame20), pc_mask);
  GTK_WIDGET_SET_FLAGS (pc_mask, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (pc_mask, GTK_CAN_DEFAULT);

  frame21 = gtk_frame_new (NULL);
  gtk_widget_ref (frame21);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame21", frame21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame21);
  gtk_table_attach (GTK_TABLE (table4), frame21, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame21), GTK_SHADOW_IN);

  pc_addr = create_hexentry ("pc_addr", NULL, NULL, 0, 0);
  gtk_widget_ref (pc_addr);
  gtk_object_set_data_full (GTK_OBJECT (app), "pc_addr", pc_addr,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pc_addr);
  gtk_container_add (GTK_CONTAINER (frame21), pc_addr);
  GTK_WIDGET_SET_FLAGS (pc_addr, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (pc_addr, GTK_CAN_DEFAULT);

  label31 = gtk_label_new (_("PC ADDR:"));
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (app), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table4), label31, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  label29 = gtk_label_new (_("DATA ADDR:"));
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (app), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table4), label29, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("PC MASK:"));
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (app), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table4), label30, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label28 = gtk_label_new (_("DATA MASK:"));
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (app), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table4), label28, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  frame_results = gtk_frame_new (_("Search Results"));
  gtk_widget_ref (frame_results);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame_results", frame_results,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_results);
  gtk_container_add (GTK_CONTAINER (vpaned2), frame_results);

  search_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (search_scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (app), "search_scrolledwindow", search_scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (search_scrolledwindow);
  gtk_container_add (GTK_CONTAINER (frame_results), search_scrolledwindow);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (search_scrolledwindow), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  search_clist = gtk_clist_new (3);
  gtk_widget_ref (search_clist);
  gtk_object_set_data_full (GTK_OBJECT (app), "search_clist", search_clist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (search_clist);
  gtk_container_add (GTK_CONTAINER (search_scrolledwindow), search_clist);
  gtk_clist_set_column_width (GTK_CLIST (search_clist), 0, 93);
  gtk_clist_set_column_width (GTK_CLIST (search_clist), 1, 92);
  gtk_clist_set_column_width (GTK_CLIST (search_clist), 2, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (search_clist), GTK_SELECTION_BROWSE);
  gtk_clist_column_titles_show (GTK_CLIST (search_clist));

  label9 = gtk_label_new (_("Address"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (app), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_clist_set_column_widget (GTK_CLIST (search_clist), 0, label9);
  gtk_misc_set_alignment (GTK_MISC (label9), 7.45058e-09, 0.5);

  valueofshit = gtk_label_new (_("Value"));
  gtk_widget_ref (valueofshit);
  gtk_object_set_data_full (GTK_OBJECT (app), "valueofshit", valueofshit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (valueofshit);
  gtk_clist_set_column_widget (GTK_CLIST (search_clist), 1, valueofshit);
  gtk_misc_set_alignment (GTK_MISC (valueofshit), 7.45058e-09, 0.5);

  label10 = gtk_label_new (_("Opcode"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (app), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_clist_set_column_widget (GTK_CLIST (search_clist), 2, label10);
  gtk_misc_set_alignment (GTK_MISC (label10), 7.45058e-09, 0.5);

  appbar = gnome_appbar_new (FALSE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_ref (appbar);
  gtk_object_set_data_full (GTK_OBJECT (app), "appbar", appbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (appbar);
  gnome_app_set_statusbar (GNOME_APP (app), appbar);

  gtk_signal_connect (GTK_OBJECT (app), "delete_event",
                      GTK_SIGNAL_FUNC (on_app_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_reset), "clicked",
                      GTK_SIGNAL_FUNC (on_button_reset_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_resume), "clicked",
                      GTK_SIGNAL_FUNC (on_button_resume_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_halt), "clicked",
                      GTK_SIGNAL_FUNC (on_button_halt_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_step), "clicked",
                      GTK_SIGNAL_FUNC (on_button_step_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_resume_with_server), "clicked",
                      GTK_SIGNAL_FUNC (on_button_resume_with_server_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_exit), "clicked",
                      GTK_SIGNAL_FUNC (on_button_exit_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (log_clear), "clicked",
                      GTK_SIGNAL_FUNC (on_log_clear_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (log_status), "clicked",
                      GTK_SIGNAL_FUNC (on_log_status_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (log_versions), "clicked",
                      GTK_SIGNAL_FUNC (on_log_versions_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bookmark_clist), "select_row",
                      GTK_SIGNAL_FUNC (on_bookmark_clist_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bookmark_clist), "unselect_row",
                      GTK_SIGNAL_FUNC (on_bookmark_clist_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry_comment), "changed",
                      GTK_SIGNAL_FUNC (on_entry_comment_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bookmark_add), "clicked",
                      GTK_SIGNAL_FUNC (on_bookmark_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bookmark_remove), "clicked",
                      GTK_SIGNAL_FUNC (on_bookmark_remove_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bookmark_save), "clicked",
                      GTK_SIGNAL_FUNC (on_bookmark_save_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bookmark_load), "clicked",
                      GTK_SIGNAL_FUNC (on_bookmark_load_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bookmark_clear), "clicked",
                      GTK_SIGNAL_FUNC (on_bookmark_clear_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exe_run), "clicked",
                      GTK_SIGNAL_FUNC (on_exe_run_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exe_info), "clicked",
                      GTK_SIGNAL_FUNC (on_exe_info_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exe_save), "clicked",
                      GTK_SIGNAL_FUNC (on_exe_save_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exe_load), "clicked",
                      GTK_SIGNAL_FUNC (on_exe_load_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (search_entry), "activate",
                      GTK_SIGNAL_FUNC (on_search_entry_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load_memory), "clicked",
                      GTK_SIGNAL_FUNC (on_load_memory_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bkpt_clist), "select_row",
                      GTK_SIGNAL_FUNC (on_bkpt_clist_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bkpt_clist), "unselect_row",
                      GTK_SIGNAL_FUNC (on_bkpt_clist_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bkpt_add), "clicked",
                      GTK_SIGNAL_FUNC (on_bkpt_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bkpt_remove), "clicked",
                      GTK_SIGNAL_FUNC (on_bkpt_remove_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bkpt_enable), "toggled",
                      GTK_SIGNAL_FUNC (on_bkpt_enable_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bkpt_hardware), "toggled",
                      GTK_SIGNAL_FUNC (on_bkpt_hardware_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (search_clist), "select_row",
                      GTK_SIGNAL_FUNC (on_search_clist_select_row),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (app), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (app), accel_group);

  return app;
}

GtkWidget*
create_about (void)
{
  const gchar *authors[] = {
    "Daniel Balster <dbalster@psxdev.de>",
    NULL
  };
  GtkWidget *about;

  about = gnome_about_new ("Debug", VERSION,
                        _("Copyright (C) 1999, 2000 by Daniel Balster"),
                        authors,
                        _("simple r3k realtime/remote debugger"),
                        "psxdebug/logo.png");
  gtk_object_set_data (GTK_OBJECT (about), "about", about);
  gtk_window_set_modal (GTK_WINDOW (about), TRUE);

  return about;
}

GtkWidget*
create_messagebox1 (void)
{
  GtkWidget *messagebox1;
  GtkWidget *dialog_vbox1;
  GtkWidget *button23;
  GtkWidget *dialog_action_area1;

  messagebox1 = gnome_message_box_new (_("There is no program running on\nthe remote target. Please start a\nprogram first."),
                              GNOME_MESSAGE_BOX_WARNING, NULL);
  gtk_object_set_data (GTK_OBJECT (messagebox1), "messagebox1", messagebox1);
  GTK_WINDOW (messagebox1)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_modal (GTK_WINDOW (messagebox1), TRUE);
  gtk_window_set_policy (GTK_WINDOW (messagebox1), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (messagebox1), TRUE);

  dialog_vbox1 = GNOME_DIALOG (messagebox1)->vbox;
  gtk_object_set_data (GTK_OBJECT (messagebox1), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  gnome_dialog_append_button (GNOME_DIALOG (messagebox1), GNOME_STOCK_BUTTON_OK);
  button23 = g_list_last (GNOME_DIALOG (messagebox1)->buttons)->data;
  gtk_widget_ref (button23);
  gtk_object_set_data_full (GTK_OBJECT (messagebox1), "button23", button23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button23);
  GTK_WIDGET_SET_FLAGS (button23, GTK_CAN_DEFAULT);

  dialog_action_area1 = GNOME_DIALOG (messagebox1)->action_area;
  gtk_widget_ref (dialog_action_area1);
  gtk_object_set_data_full (GTK_OBJECT (messagebox1), "dialog_action_area1", dialog_action_area1,
                            (GtkDestroyNotify) gtk_widget_unref);

  return messagebox1;
}

GtkWidget*
create_messagebox2 (void)
{
  GtkWidget *messagebox2;
  GtkWidget *dialog_vbox2;
  GtkWidget *button24;
  GtkWidget *dialog_action_area2;

  messagebox2 = gnome_message_box_new (_("Communication link seems to be broken!\nPlease restart the target machine and re-\nupload the program and try again. Sorry."),
                              GNOME_MESSAGE_BOX_ERROR, NULL);
  gtk_object_set_data (GTK_OBJECT (messagebox2), "messagebox2", messagebox2);
  GTK_WINDOW (messagebox2)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_modal (GTK_WINDOW (messagebox2), TRUE);
  gtk_window_set_policy (GTK_WINDOW (messagebox2), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (messagebox2), TRUE);

  dialog_vbox2 = GNOME_DIALOG (messagebox2)->vbox;
  gtk_object_set_data (GTK_OBJECT (messagebox2), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  gnome_dialog_append_button (GNOME_DIALOG (messagebox2), GNOME_STOCK_BUTTON_OK);
  button24 = g_list_last (GNOME_DIALOG (messagebox2)->buttons)->data;
  gtk_widget_ref (button24);
  gtk_object_set_data_full (GTK_OBJECT (messagebox2), "button24", button24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button24);
  GTK_WIDGET_SET_FLAGS (button24, GTK_CAN_DEFAULT);

  dialog_action_area2 = GNOME_DIALOG (messagebox2)->action_area;
  gtk_widget_ref (dialog_action_area2);
  gtk_object_set_data_full (GTK_OBJECT (messagebox2), "dialog_action_area2", dialog_action_area2,
                            (GtkDestroyNotify) gtk_widget_unref);

  return messagebox2;
}

GtkWidget*
create_box_filename_needed (void)
{
  GtkWidget *box_filename_needed;
  GtkWidget *dialog_vbox3;
  GtkWidget *button30;
  GtkWidget *dialog_action_area3;

  box_filename_needed = gnome_message_box_new (_("No executable filename given!\nPlease correct that."),
                              GNOME_MESSAGE_BOX_WARNING, NULL);
  gtk_object_set_data (GTK_OBJECT (box_filename_needed), "box_filename_needed", box_filename_needed);
  GTK_WINDOW (box_filename_needed)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_modal (GTK_WINDOW (box_filename_needed), TRUE);
  gtk_window_set_policy (GTK_WINDOW (box_filename_needed), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (box_filename_needed), TRUE);

  dialog_vbox3 = GNOME_DIALOG (box_filename_needed)->vbox;
  gtk_object_set_data (GTK_OBJECT (box_filename_needed), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  gnome_dialog_append_button (GNOME_DIALOG (box_filename_needed), GNOME_STOCK_BUTTON_OK);
  button30 = g_list_last (GNOME_DIALOG (box_filename_needed)->buttons)->data;
  gtk_widget_ref (button30);
  gtk_object_set_data_full (GTK_OBJECT (box_filename_needed), "button30", button30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button30);
  GTK_WIDGET_SET_FLAGS (button30, GTK_CAN_DEFAULT);

  dialog_action_area3 = GNOME_DIALOG (box_filename_needed)->action_area;
  gtk_widget_ref (dialog_action_area3);
  gtk_object_set_data_full (GTK_OBJECT (box_filename_needed), "dialog_action_area3", dialog_action_area3,
                            (GtkDestroyNotify) gtk_widget_unref);

  return box_filename_needed;
}

GtkWidget*
create_box_debugexe_needed (void)
{
  GtkWidget *box_debugexe_needed;
  GtkWidget *dialog_vbox4;
  GtkWidget *button31;
  GtkWidget *dialog_action_area4;

  box_debugexe_needed = gnome_message_box_new (_("A debugging version of your\nexecutable binary is needed for this."),
                              GNOME_MESSAGE_BOX_WARNING, NULL);
  gtk_object_set_data (GTK_OBJECT (box_debugexe_needed), "box_debugexe_needed", box_debugexe_needed);
  GTK_WINDOW (box_debugexe_needed)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_modal (GTK_WINDOW (box_debugexe_needed), TRUE);
  gtk_window_set_policy (GTK_WINDOW (box_debugexe_needed), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (box_debugexe_needed), TRUE);

  dialog_vbox4 = GNOME_DIALOG (box_debugexe_needed)->vbox;
  gtk_object_set_data (GTK_OBJECT (box_debugexe_needed), "dialog_vbox4", dialog_vbox4);
  gtk_widget_show (dialog_vbox4);

  gnome_dialog_append_button (GNOME_DIALOG (box_debugexe_needed), GNOME_STOCK_BUTTON_OK);
  button31 = g_list_last (GNOME_DIALOG (box_debugexe_needed)->buttons)->data;
  gtk_widget_ref (button31);
  gtk_object_set_data_full (GTK_OBJECT (box_debugexe_needed), "button31", button31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button31);
  GTK_WIDGET_SET_FLAGS (button31, GTK_CAN_DEFAULT);

  dialog_action_area4 = GNOME_DIALOG (box_debugexe_needed)->action_area;
  gtk_widget_ref (dialog_action_area4);
  gtk_object_set_data_full (GTK_OBJECT (box_debugexe_needed), "dialog_action_area4", dialog_action_area4,
                            (GtkDestroyNotify) gtk_widget_unref);

  return box_debugexe_needed;
}

