/* Automatically generated by po2tbl.sed from libtim.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"libtim: freeing tim image with bad magic!\n", 2},
};

int _msg_tbl_length = 2;
