/* Automatically generated by po2tbl.sed from psxcurvegen.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"PSXDEV Curve Generator", 2},
  {"New", 3},
  {"New File", 4},
  {"Open", 5},
  {"Open File", 6},
  {"Save", 7},
  {"Save File", 8},
  {"Save As", 9},
  {"Address of curve in PlayStation memory...", 10},
  {"Upload", 11},
  {"SPLINE", 12},
  {"LINEAR", 13},
  {"FREE", 14},
  {"Min X", 15},
  {"Max X", 16},
  {"Min Y", 17},
  {"Max Y", 18},
  {"Count", 19},
  {"Type", 20},
  {"u_char", 21},
  {"char", 22},
  {"u_short", 23},
  {"short", 24},
  {"u_long", 25},
  {"long", 26},
  {"float", 27},
  {"double", 28},
  {"fixed (4+12)", 29},
  {"Curve Interval:", 30},
  {"Datatype:", 31},
  {"Scale", 32},
  {"Base", 33},
  {"Name", 34},
  {"Add", 35},
  {"Remove", 36},
  {"Use", 37},
  {"Copyright (C) 1999, 2000 by Daniel Balster", 38},
  {"A very simple curve generator", 39},
  {"Couldn't find pixmap file: %s", 40},
  {"Couldn't create pixmap from file: %s", 41},
};

int _msg_tbl_length = 41;
