/* Automatically generated by po2tbl.sed from psxcdmaker.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"PSXDEV CD-ROM Maker", 2},
  {"New", 3},
  {"Open", 4},
  {"Reload current settings from local project file", 5},
  {"Save", 6},
  {"Save current settings to .psxcdmakerrc", 7},
  {"Master", 8},
  {"Master CD image", 9},
  {"Write", 10},
  {"Write CD image to CD writer", 11},
  {"Exit", 12},
  {"Exit application", 13},
  {"label34", 14},
  {"Help", 15},
  {"Input Path", 16},
  {"%V MB used", 17},
  {"Disk _Usage", 18},
  {"Perform \"du -sm\" and display it based on a 750 MB scale", 19},
  {"Output Path", 20},
  {"%V of %U MB left (%P %%)", 21},
  {"Paths", 22},
  {"Filesystem Header", 23},
  {"\
The Volume Identifier. There is space on the disc for 32 characters of \
information.", 24},
  {"VOLUME_ID", 25},
  {"\
The Volume Set Name. There is space on the disc for 128 characters of \
information.", 26},
  {"VOLUME_SET", 27},
  {"\
This should describe the publisher of the CDROM, usually with a mailing \
address and phone number. There is space on the disc for 128 characters of \
information.", 28},
  {"PUBLISHER", 29},
  {"\
This should describe the preparer of the CDROM, usually with a mailing \
address and phone number. There is space on the disc for 128 characters of \
information.", 30},
  {"DATA_PREPARER", 31},
  {"\
The application identifier should describe the application that will be on \
the disc. There is space on the disc for 128 characters of information.", 32},
  {"PLAYSTATION", 33},
  {"\
The System Identifier. There is space on the disc for 32 characters of \
information.", 34},
  {"Volume ID:", 35},
  {"Volume Set:", 36},
  {"Publisher:", 37},
  {"Data Preparer:", 38},
  {"Application ID:", 39},
  {"System ID:", 40},
  {"Information Files", 41},
  {"\
The  bibliographic information, often the name of a file on the disc \
containing a bibliography. There is space in the disc for 37 characters of \
information.", 42},
  {"\
The copyright information, often the name of a file on the disc containing \
the copyright notice. There is space in the disc for 37 characters of \
information.", 43},
  {"\
The  abstract information, often the name of a file on the disc containing \
an abstract. There is space in the disc for 37 characters of information.", 44},
  {"Abstract:", 45},
  {"Copyright:", 46},
  {"Bibliography:", 47},
  {"Miscellaneous", 48},
  {"Follow Symbolic Links", 49},
  {"Include All Files", 50},
  {"Allow files to begin with period", 51},
  {"Omit trailing periods", 52},
  {"Times and Dates", 53},
  {"Creation:", 54},
  {"Expiration:", 55},
  {"Modification:", 56},
  {"Effective:", 57},
  {"Comment", 58},
  {"ISO9660", 59},
  {"SYSTEM.CNF;1", 60},
  {"_Generate SYSTEM.CNF;1", 61},
  {"0x4", 62},
  {"0x10", 63},
  {"0x801FFFF0", 64},
  {"cdrom:ABCD_000.00;1", 65},
  {"TCB=", 66},
  {"EVENT=", 67},
  {"STACK=", 68},
  {"BOOT=", 69},
  {"License file:", 70},
  {"Exclusion List", 71},
  {"\
All files which match a pattern in this list are excluded from the CD-ROM", 72},
  {"_Add", 73},
  {"_Remove", 74},
  {"_Clear", 75},
  {"XA File Inclusion List", 76},
  {"\
All files which match a pattern in this list are embedded as XA files (2336 \
bytes/sector)", 77},
  {"PSX", 78},
  {"Track List", 79},
  {"Filename", 80},
  {"Size", 81},
  {"Copy", 82},
  {"Preemp.", 83},
  {"Type", 84},
  {"Re_fresh", 85},
  {"_CopyPerm.", 86},
  {"_Preemp.", 87},
  {"Audio", 88},
  {"CDR DAO", 89},
  {"if this field is /dev/cdrecorder is used", 90},
  {"0,5,0", 91},
  {"cdd2600", 92},
  {"plextor", 93},
  {"plextor-scan", 94},
  {"generic-mmc", 95},
  {"generic-mmc-raw", 96},
  {"ricoh-mp6200", 97},
  {"yamaha-cdr10x", 98},
  {"teac-cdr55", 99},
  {"sony-cdu920", 100},
  {"sony-cdu948", 101},
  {"taiyo-yuden", 102},
  {"if this field is empty the driver is detected automatically", 103},
  {"Device:", 104},
  {"Driver:", 105},
  {"Speed:", 106},
  {"Buffers:", 107},
  {"enter 0 for maximum speed", 108},
  {"CDR DAO Options", 109},
  {"Simulate (turn laser off)", 110},
  {"Eject", 111},
  {"Force", 112},
  {"No 10 seconds pause", 113},
  {"Reload tray", 114},
  {"Swab audio byte order", 115},
  {"On the fly", 116},
  {"Edit TOC", 117},
  {"TOC", 118},
  {"CD-Writer", 119},
  {"Reset", 120},
  {"Kill", 121},
  {"Shell", 122},
  {"Commands", 123},
  {"/bin/bash", 124},
  {"du -sm", 125},
  {"psx-mkisofs", 126},
  {"cdrdao", 127},
  {"SHELL:", 128},
  {"DISKUSAGE:", 129},
  {"MKISOFS:", 130},
  {"CDRDAO:", 131},
  {"Temporary Names", 132},
  {"image.toc", 133},
  {"image.iso", 134},
  {"ISO image filename:", 135},
  {"TOC sheet filename:", 136},
  {"Config", 137},
  {"Copyright (C) 2000 by Daniel Balster", 138},
  {"A simple frontend for CDRDAO and MKISOFS ", 139},
  {"Couldn't find pixmap file: %s", 140},
  {"Couldn't create pixmap from file: %s", 141},
};

int _msg_tbl_length = 141;
