/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Revert"),
    NULL,
    on_open2_clicked, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_REVERT,
    GDK_R, GDK_CONTROL_MASK, NULL
  },
  GNOMEUIINFO_MENU_EXIT_ITEM (on_exit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file1_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (help1_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_app (void)
{
  GtkWidget *app;
  GtkWidget *dock1;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *open;
  GtkWidget *resume;
  GtkWidget *halt;
  GtkWidget *reset;
  GtkWidget *vbox1;
  GtkWidget *scrolledwindow;
  GtkWidget *clist;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *frame1;
  GtkWidget *table1;
  GtkWidget *B_char;
  GtkWidget *B_uchar;
  GtkWidget *B_short;
  GtkWidget *B_ushort;
  GtkWidget *B_long;
  GtkWidget *B_ulong;
  GtkWidget *B_svector;
  GtkWidget *B_vector;
  GtkWidget *B_matrix;
  GtkWidget *B_cvector;
  GtkWidget *B_rect;
  GtkWidget *B_toggle;
  GtkWidget *appbar1;

  app = gnome_app_new ("Interactor", _("PSXDEV Interactor"));
  gtk_object_set_data (GTK_OBJECT (app), "app", app);

  dock1 = GNOME_APP (app)->dock;
  gtk_widget_ref (dock1);
  gtk_object_set_data_full (GTK_OBJECT (app), "dock1", dock1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dock1);

  gnome_app_create_menus (GNOME_APP (app), menubar1_uiinfo);

  gtk_widget_ref (menubar1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "file1",
                            menubar1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "revert1",
                            file1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "exit1",
                            file1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "help1",
                            menubar1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (app), "about1",
                            help1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (app), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gnome_app_add_toolbar (GNOME_APP (app), GTK_TOOLBAR (toolbar1), "toolbar1",
                                GNOME_DOCK_ITEM_BEH_EXCLUSIVE,
                                GNOME_DOCK_TOP, 1, 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 1);
  gtk_toolbar_set_space_size (GTK_TOOLBAR (toolbar1), 16);
  gtk_toolbar_set_space_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_SPACE_LINE);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar1), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_REVERT);
  open = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Revert"),
                                _("Open File"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (open);
  gtk_object_set_data_full (GTK_OBJECT (app), "open", open,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_TIMER);
  resume = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Resume"),
                                _("Clear Selection"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (resume);
  gtk_object_set_data_full (GTK_OBJECT (app), "resume", resume,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (resume);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_TIMER_STOP);
  halt = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Halt"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (halt);
  gtk_object_set_data_full (GTK_OBJECT (app), "halt", halt,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (halt);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (app, GNOME_STOCK_PIXMAP_REFRESH);
  reset = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Reset"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (reset);
  gtk_object_set_data_full (GTK_OBJECT (app), "reset", reset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reset);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (app), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gnome_app_set_contents (GNOME_APP (app), vbox1);

  scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (app), "scrolledwindow", scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist = gtk_clist_new (3);
  gtk_widget_ref (clist);
  gtk_object_set_data_full (GTK_OBJECT (app), "clist", clist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow), clist);
  gtk_clist_set_column_width (GTK_CLIST (clist), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist), 2, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist));

  label17 = gtk_label_new (_("Address"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (app), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_clist_set_column_widget (GTK_CLIST (clist), 0, label17);

  label18 = gtk_label_new (_("Type"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (app), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_clist_set_column_widget (GTK_CLIST (clist), 1, label18);

  label19 = gtk_label_new (_("Variable Name"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (app), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_clist_set_column_widget (GTK_CLIST (clist), 2, label19);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (app), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, FALSE, TRUE, 0);

  table1 = gtk_table_new (2, 6, TRUE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (app), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame1), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);

  B_char = gtk_button_new_with_label (_("CHAR"));
  gtk_widget_ref (B_char);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_char", B_char,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_char);
  gtk_table_attach (GTK_TABLE (table1), B_char, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_char, FALSE);

  B_uchar = gtk_button_new_with_label (_("UCHAR"));
  gtk_widget_ref (B_uchar);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_uchar", B_uchar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_uchar);
  gtk_table_attach (GTK_TABLE (table1), B_uchar, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_uchar, FALSE);

  B_short = gtk_button_new_with_label (_("SHORT"));
  gtk_widget_ref (B_short);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_short", B_short,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_short);
  gtk_table_attach (GTK_TABLE (table1), B_short, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_short, FALSE);

  B_ushort = gtk_button_new_with_label (_("USHORT"));
  gtk_widget_ref (B_ushort);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_ushort", B_ushort,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_ushort);
  gtk_table_attach (GTK_TABLE (table1), B_ushort, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_ushort, FALSE);

  B_long = gtk_button_new_with_label (_("LONG"));
  gtk_widget_ref (B_long);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_long", B_long,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_long);
  gtk_table_attach (GTK_TABLE (table1), B_long, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_long, FALSE);

  B_ulong = gtk_button_new_with_label (_("ULONG"));
  gtk_widget_ref (B_ulong);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_ulong", B_ulong,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_ulong);
  gtk_table_attach (GTK_TABLE (table1), B_ulong, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_ulong, FALSE);

  B_svector = gtk_button_new_with_label (_("SVECTOR"));
  gtk_widget_ref (B_svector);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_svector", B_svector,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_svector);
  gtk_table_attach (GTK_TABLE (table1), B_svector, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_svector, FALSE);

  B_vector = gtk_button_new_with_label (_("VECTOR"));
  gtk_widget_ref (B_vector);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_vector", B_vector,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_vector);
  gtk_table_attach (GTK_TABLE (table1), B_vector, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_vector, FALSE);

  B_matrix = gtk_button_new_with_label (_("MATRIX"));
  gtk_widget_ref (B_matrix);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_matrix", B_matrix,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_matrix);
  gtk_table_attach (GTK_TABLE (table1), B_matrix, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_matrix, FALSE);

  B_cvector = gtk_button_new_with_label (_("CVECTOR"));
  gtk_widget_ref (B_cvector);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_cvector", B_cvector,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_cvector);
  gtk_table_attach (GTK_TABLE (table1), B_cvector, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_cvector, FALSE);

  B_rect = gtk_button_new_with_label (_("RECT"));
  gtk_widget_ref (B_rect);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_rect", B_rect,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_rect);
  gtk_table_attach (GTK_TABLE (table1), B_rect, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_rect, FALSE);

  B_toggle = gtk_button_new_with_label (_("0/1 Toggle"));
  gtk_widget_ref (B_toggle);
  gtk_object_set_data_full (GTK_OBJECT (app), "B_toggle", B_toggle,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (B_toggle);
  gtk_table_attach (GTK_TABLE (table1), B_toggle, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (B_toggle, FALSE);

  appbar1 = gnome_appbar_new (TRUE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_ref (appbar1);
  gtk_object_set_data_full (GTK_OBJECT (app), "appbar1", appbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (appbar1);
  gnome_app_set_statusbar (GNOME_APP (app), appbar1);

  gtk_signal_connect (GTK_OBJECT (app), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (open), "clicked",
                      GTK_SIGNAL_FUNC (on_open_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (resume), "clicked",
                      GTK_SIGNAL_FUNC (on_resume_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (halt), "clicked",
                      GTK_SIGNAL_FUNC (on_halt_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reset), "clicked",
                      GTK_SIGNAL_FUNC (on_reset_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist), "select_row",
                      GTK_SIGNAL_FUNC (on_clist_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist), "unselect_row",
                      GTK_SIGNAL_FUNC (on_clist_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist), "unselect_all",
                      GTK_SIGNAL_FUNC (on_clist_unselect_all),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_char), "clicked",
                      GTK_SIGNAL_FUNC (on_B_char_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_uchar), "clicked",
                      GTK_SIGNAL_FUNC (on_B_uchar_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_short), "clicked",
                      GTK_SIGNAL_FUNC (on_B_short_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_ushort), "clicked",
                      GTK_SIGNAL_FUNC (on_B_ushort_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_long), "clicked",
                      GTK_SIGNAL_FUNC (on_B_long_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_ulong), "clicked",
                      GTK_SIGNAL_FUNC (on_B_ulong_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_svector), "clicked",
                      GTK_SIGNAL_FUNC (on_B_svector_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_vector), "clicked",
                      GTK_SIGNAL_FUNC (on_B_vector_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_matrix), "clicked",
                      GTK_SIGNAL_FUNC (on_B_matrix_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_cvector), "clicked",
                      GTK_SIGNAL_FUNC (on_B_cvector_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_rect), "clicked",
                      GTK_SIGNAL_FUNC (on_B_rect_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (B_toggle), "clicked",
                      GTK_SIGNAL_FUNC (on_B_toggle_clicked),
                      NULL);

  return app;
}

GtkWidget*
create_about (void)
{
  const gchar *authors[] = {
    "Daniel Balster <dbalster@psxdev.de>",
    NULL
  };
  GtkWidget *about;

  about = gnome_about_new ("Interactor", VERSION,
                        _("Copyright (C) 1999 by Daniel Balster"),
                        authors,
                        _("Modify data types on a remote target in realtime"),
                        "psxinteractor/logo.png");
  gtk_object_set_data (GTK_OBJECT (about), "about", about);
  gtk_window_set_modal (GTK_WINDOW (about), TRUE);

  gtk_signal_connect (GTK_OBJECT (about), "clicked",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about), "close",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);

  return about;
}

GtkWidget*
create_window_uchar (void)
{
  GtkWidget *window_uchar;
  GtkWidget *hbox5;
  GtkWidget *Q_uchar_reload;
  GtkObject *Q_uchar_adj;
  GtkWidget *Q_uchar;

  window_uchar = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_uchar), "window_uchar", window_uchar);
  gtk_window_set_title (GTK_WINDOW (window_uchar), _("window_uchar"));
  gtk_window_set_policy (GTK_WINDOW (window_uchar), TRUE, TRUE, TRUE);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (window_uchar), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (window_uchar), hbox5);

  Q_uchar_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_uchar_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_uchar), "Q_uchar_reload", Q_uchar_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_uchar_reload);
  gtk_box_pack_start (GTK_BOX (hbox5), Q_uchar_reload, FALSE, FALSE, 0);

  Q_uchar_adj = gtk_adjustment_new (0, 0, 255, 1, 8, 8);
  Q_uchar = gtk_spin_button_new (GTK_ADJUSTMENT (Q_uchar_adj), 1, 0);
  gtk_widget_ref (Q_uchar);
  gtk_object_set_data_full (GTK_OBJECT (window_uchar), "Q_uchar", Q_uchar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_uchar);
  gtk_box_pack_start (GTK_BOX (hbox5), Q_uchar, TRUE, TRUE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_uchar), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_uchar), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_uchar_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_uchar_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_uchar), "changed",
                      GTK_SIGNAL_FUNC (on_Q_uchar_changed),
                      NULL);

  return window_uchar;
}

GtkWidget*
create_window_char (void)
{
  GtkWidget *window_char;
  GtkWidget *hbox2;
  GtkWidget *Q_char_reload;
  GtkObject *Q_char_adj;
  GtkWidget *Q_char;

  window_char = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_char), "window_char", window_char);
  gtk_window_set_title (GTK_WINDOW (window_char), _("window_char"));
  gtk_window_set_policy (GTK_WINDOW (window_char), TRUE, TRUE, TRUE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (window_char), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (window_char), hbox2);

  Q_char_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_char_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_char), "Q_char_reload", Q_char_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_char_reload);
  gtk_box_pack_start (GTK_BOX (hbox2), Q_char_reload, FALSE, FALSE, 0);

  Q_char_adj = gtk_adjustment_new (0, -128, 127, 1, 8, 8);
  Q_char = gtk_spin_button_new (GTK_ADJUSTMENT (Q_char_adj), 1, 0);
  gtk_widget_ref (Q_char);
  gtk_object_set_data_full (GTK_OBJECT (window_char), "Q_char", Q_char,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_char);
  gtk_box_pack_start (GTK_BOX (hbox2), Q_char, TRUE, TRUE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_char), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_char), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_char_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_char_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_char), "changed",
                      GTK_SIGNAL_FUNC (on_Q_char_changed),
                      NULL);

  return window_char;
}

GtkWidget*
create_window_ushort (void)
{
  GtkWidget *window_ushort;
  GtkWidget *hbox3;
  GtkWidget *Q_ushort_reload;
  GtkObject *Q_ushort_adj;
  GtkWidget *Q_ushort;

  window_ushort = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_ushort), "window_ushort", window_ushort);
  gtk_window_set_title (GTK_WINDOW (window_ushort), _("window_ushort"));
  gtk_window_set_policy (GTK_WINDOW (window_ushort), TRUE, TRUE, TRUE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (window_ushort), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (window_ushort), hbox3);

  Q_ushort_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_ushort_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_ushort), "Q_ushort_reload", Q_ushort_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_ushort_reload);
  gtk_box_pack_start (GTK_BOX (hbox3), Q_ushort_reload, FALSE, FALSE, 0);

  Q_ushort_adj = gtk_adjustment_new (0, 0, 65535, 1, 256, 256);
  Q_ushort = gtk_spin_button_new (GTK_ADJUSTMENT (Q_ushort_adj), 1, 0);
  gtk_widget_ref (Q_ushort);
  gtk_object_set_data_full (GTK_OBJECT (window_ushort), "Q_ushort", Q_ushort,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_ushort);
  gtk_box_pack_start (GTK_BOX (hbox3), Q_ushort, TRUE, TRUE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_ushort), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_ushort), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_ushort_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_ushort_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_ushort), "changed",
                      GTK_SIGNAL_FUNC (on_Q_ushort_changed),
                      NULL);

  return window_ushort;
}

GtkWidget*
create_window_short (void)
{
  GtkWidget *window_short;
  GtkWidget *hbox4;
  GtkWidget *Q_short_reload;
  GtkObject *Q_short_adj;
  GtkWidget *Q_short;

  window_short = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_short), "window_short", window_short);
  gtk_window_set_title (GTK_WINDOW (window_short), _("window_short"));
  gtk_window_set_policy (GTK_WINDOW (window_short), TRUE, TRUE, TRUE);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (window_short), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (window_short), hbox4);

  Q_short_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_short_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_short), "Q_short_reload", Q_short_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_short_reload);
  gtk_box_pack_start (GTK_BOX (hbox4), Q_short_reload, FALSE, FALSE, 0);

  Q_short_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_short = gtk_spin_button_new (GTK_ADJUSTMENT (Q_short_adj), 1, 0);
  gtk_widget_ref (Q_short);
  gtk_object_set_data_full (GTK_OBJECT (window_short), "Q_short", Q_short,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_short);
  gtk_box_pack_start (GTK_BOX (hbox4), Q_short, TRUE, TRUE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_short), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_short), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_short_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_short_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_short), "changed",
                      GTK_SIGNAL_FUNC (on_Q_short_changed),
                      NULL);

  return window_short;
}

GtkWidget*
create_window_long (void)
{
  GtkWidget *window_long;
  GtkWidget *hbox7;
  GtkWidget *Q_long_reload;
  GtkObject *Q_long_adj;
  GtkWidget *Q_long;

  window_long = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_long), "window_long", window_long);
  gtk_window_set_title (GTK_WINDOW (window_long), _("window_long"));
  gtk_window_set_policy (GTK_WINDOW (window_long), TRUE, TRUE, TRUE);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (window_long), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (window_long), hbox7);

  Q_long_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_long_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_long), "Q_long_reload", Q_long_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_long_reload);
  gtk_box_pack_start (GTK_BOX (hbox7), Q_long_reload, FALSE, FALSE, 0);

  Q_long_adj = gtk_adjustment_new (0, -2.14748e+09, 2.14748e+09, 1, 256, 256);
  Q_long = gtk_spin_button_new (GTK_ADJUSTMENT (Q_long_adj), 1, 0);
  gtk_widget_ref (Q_long);
  gtk_object_set_data_full (GTK_OBJECT (window_long), "Q_long", Q_long,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_long);
  gtk_box_pack_start (GTK_BOX (hbox7), Q_long, TRUE, TRUE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_long), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_long), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_long_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_long_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_long), "changed",
                      GTK_SIGNAL_FUNC (on_Q_long_changed),
                      NULL);

  return window_long;
}

GtkWidget*
create_window_ulong (void)
{
  GtkWidget *window_ulong;
  GtkWidget *hbox6;
  GtkWidget *Q_ulong_reload;
  GtkObject *Q_ulong_adj;
  GtkWidget *Q_ulong;

  window_ulong = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_ulong), "window_ulong", window_ulong);
  gtk_window_set_title (GTK_WINDOW (window_ulong), _("window_ulong"));
  gtk_window_set_policy (GTK_WINDOW (window_ulong), TRUE, TRUE, TRUE);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (window_ulong), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (window_ulong), hbox6);

  Q_ulong_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_ulong_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_ulong), "Q_ulong_reload", Q_ulong_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_ulong_reload);
  gtk_box_pack_start (GTK_BOX (hbox6), Q_ulong_reload, FALSE, TRUE, 0);

  Q_ulong_adj = gtk_adjustment_new (0, 0, 4.29497e+09, 1, 10, 10);
  Q_ulong = gtk_spin_button_new (GTK_ADJUSTMENT (Q_ulong_adj), 1, 0);
  gtk_widget_ref (Q_ulong);
  gtk_object_set_data_full (GTK_OBJECT (window_ulong), "Q_ulong", Q_ulong,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_ulong);
  gtk_box_pack_start (GTK_BOX (hbox6), Q_ulong, TRUE, TRUE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_ulong), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_ulong), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_ulong_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_ulong_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_ulong), "changed",
                      GTK_SIGNAL_FUNC (on_Q_ulong_changed),
                      NULL);

  return window_ulong;
}

GtkWidget*
create_window_svector (void)
{
  GtkWidget *window_svector;
  GtkWidget *vbox8;
  GtkWidget *Q_svector_reload;
  GtkObject *Q_svector_x_adj;
  GtkWidget *Q_svector_x;
  GtkObject *Q_svector_y_adj;
  GtkWidget *Q_svector_y;
  GtkObject *Q_svector_z_adj;
  GtkWidget *Q_svector_z;

  window_svector = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_svector), "window_svector", window_svector);
  gtk_window_set_title (GTK_WINDOW (window_svector), _("window_svector"));
  gtk_window_set_policy (GTK_WINDOW (window_svector), TRUE, TRUE, TRUE);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (window_svector), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (window_svector), vbox8);

  Q_svector_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_svector_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_svector), "Q_svector_reload", Q_svector_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_svector_reload);
  gtk_box_pack_start (GTK_BOX (vbox8), Q_svector_reload, FALSE, FALSE, 0);

  Q_svector_x_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_svector_x = gtk_spin_button_new (GTK_ADJUSTMENT (Q_svector_x_adj), 1, 0);
  gtk_widget_ref (Q_svector_x);
  gtk_object_set_data_full (GTK_OBJECT (window_svector), "Q_svector_x", Q_svector_x,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_svector_x);
  gtk_box_pack_start (GTK_BOX (vbox8), Q_svector_x, FALSE, FALSE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_svector_x), TRUE);

  Q_svector_y_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_svector_y = gtk_spin_button_new (GTK_ADJUSTMENT (Q_svector_y_adj), 1, 0);
  gtk_widget_ref (Q_svector_y);
  gtk_object_set_data_full (GTK_OBJECT (window_svector), "Q_svector_y", Q_svector_y,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_svector_y);
  gtk_box_pack_start (GTK_BOX (vbox8), Q_svector_y, FALSE, FALSE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_svector_y), TRUE);

  Q_svector_z_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_svector_z = gtk_spin_button_new (GTK_ADJUSTMENT (Q_svector_z_adj), 1, 0);
  gtk_widget_ref (Q_svector_z);
  gtk_object_set_data_full (GTK_OBJECT (window_svector), "Q_svector_z", Q_svector_z,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_svector_z);
  gtk_box_pack_start (GTK_BOX (vbox8), Q_svector_z, FALSE, FALSE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_svector_z), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_svector), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_svector_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_svector_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_svector_x), "changed",
                      GTK_SIGNAL_FUNC (on_Q_svector_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_svector_y), "changed",
                      GTK_SIGNAL_FUNC (on_Q_svector_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_svector_z), "changed",
                      GTK_SIGNAL_FUNC (on_Q_svector_changed),
                      NULL);

  return window_svector;
}

GtkWidget*
create_window_vector (void)
{
  GtkWidget *window_vector;
  GtkWidget *vbox9;
  GtkWidget *Q_vector_reload;
  GtkObject *Q_vector_x_adj;
  GtkWidget *Q_vector_x;
  GtkObject *Q_vector_y_adj;
  GtkWidget *Q_vector_y;
  GtkObject *Q_vector_z_adj;
  GtkWidget *Q_vector_z;

  window_vector = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_vector), "window_vector", window_vector);
  gtk_window_set_title (GTK_WINDOW (window_vector), _("window_vector"));
  gtk_window_set_policy (GTK_WINDOW (window_vector), TRUE, TRUE, TRUE);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (window_vector), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (window_vector), vbox9);

  Q_vector_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_vector_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_vector), "Q_vector_reload", Q_vector_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_vector_reload);
  gtk_box_pack_start (GTK_BOX (vbox9), Q_vector_reload, FALSE, FALSE, 0);

  Q_vector_x_adj = gtk_adjustment_new (0, -2.14748e+09, 2.14748e+09, 1, 256, 256);
  Q_vector_x = gtk_spin_button_new (GTK_ADJUSTMENT (Q_vector_x_adj), 1, 0);
  gtk_widget_ref (Q_vector_x);
  gtk_object_set_data_full (GTK_OBJECT (window_vector), "Q_vector_x", Q_vector_x,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_vector_x);
  gtk_box_pack_start (GTK_BOX (vbox9), Q_vector_x, FALSE, FALSE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_vector_x), TRUE);

  Q_vector_y_adj = gtk_adjustment_new (0, -2.14748e+09, 2.14748e+09, 1, 256, 256);
  Q_vector_y = gtk_spin_button_new (GTK_ADJUSTMENT (Q_vector_y_adj), 1, 0);
  gtk_widget_ref (Q_vector_y);
  gtk_object_set_data_full (GTK_OBJECT (window_vector), "Q_vector_y", Q_vector_y,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_vector_y);
  gtk_box_pack_start (GTK_BOX (vbox9), Q_vector_y, FALSE, FALSE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_vector_y), TRUE);

  Q_vector_z_adj = gtk_adjustment_new (0, -2.14748e+09, 2.14748e+09, 1, 256, 256);
  Q_vector_z = gtk_spin_button_new (GTK_ADJUSTMENT (Q_vector_z_adj), 1, 0);
  gtk_widget_ref (Q_vector_z);
  gtk_object_set_data_full (GTK_OBJECT (window_vector), "Q_vector_z", Q_vector_z,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_vector_z);
  gtk_box_pack_start (GTK_BOX (vbox9), Q_vector_z, FALSE, FALSE, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_vector_z), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_vector), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_vector_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_vector_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_vector_x), "changed",
                      GTK_SIGNAL_FUNC (on_Q_vector_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_vector_y), "changed",
                      GTK_SIGNAL_FUNC (on_Q_vector_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_vector_z), "changed",
                      GTK_SIGNAL_FUNC (on_Q_vector_changed),
                      NULL);

  return window_vector;
}

GtkWidget*
create_window_matrix (void)
{
  GtkWidget *window_matrix;
  GtkWidget *vbox10;
  GtkWidget *Q_matrix_reload;
  GtkWidget *table2;
  GtkObject *Q_matrix_a13_adj;
  GtkWidget *Q_matrix_a13;
  GtkObject *Q_matrix_a33_adj;
  GtkWidget *Q_matrix_a33;
  GtkObject *Q_matrix_a23_adj;
  GtkWidget *Q_matrix_a23;
  GtkObject *Q_matrix_a12_adj;
  GtkWidget *Q_matrix_a12;
  GtkObject *Q_matrix_a22_adj;
  GtkWidget *Q_matrix_a22;
  GtkObject *Q_matrix_a32_adj;
  GtkWidget *Q_matrix_a32;
  GtkObject *Q_matrix_a11_adj;
  GtkWidget *Q_matrix_a11;
  GtkObject *Q_matrix_a21_adj;
  GtkWidget *Q_matrix_a21;
  GtkObject *Q_matrix_a31_adj;
  GtkWidget *Q_matrix_a31;

  window_matrix = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_matrix), "window_matrix", window_matrix);
  gtk_window_set_title (GTK_WINDOW (window_matrix), _("window_matrix"));
  gtk_window_set_policy (GTK_WINDOW (window_matrix), TRUE, TRUE, TRUE);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (window_matrix), vbox10);

  Q_matrix_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_matrix_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_reload", Q_matrix_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_reload);
  gtk_box_pack_start (GTK_BOX (vbox10), Q_matrix_reload, FALSE, FALSE, 0);

  table2 = gtk_table_new (3, 3, TRUE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox10), table2, FALSE, FALSE, 0);

  Q_matrix_a13_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a13 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a13_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a13);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a13", Q_matrix_a13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a13);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a13, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a13), TRUE);

  Q_matrix_a33_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a33 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a33_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a33);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a33", Q_matrix_a33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a33);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a33, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a33), TRUE);

  Q_matrix_a23_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a23 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a23_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a23);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a23", Q_matrix_a23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a23);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a23, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a23), TRUE);

  Q_matrix_a12_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a12 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a12_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a12);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a12", Q_matrix_a12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a12);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a12, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a12), TRUE);

  Q_matrix_a22_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a22 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a22_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a22);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a22", Q_matrix_a22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a22);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a22, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a22), TRUE);

  Q_matrix_a32_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a32 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a32_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a32);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a32", Q_matrix_a32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a32);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a32, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a32), TRUE);

  Q_matrix_a11_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a11 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a11_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a11);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a11", Q_matrix_a11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a11);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a11, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a11), TRUE);

  Q_matrix_a21_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a21 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a21_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a21);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a21", Q_matrix_a21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a21);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a21, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a21), TRUE);

  Q_matrix_a31_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_matrix_a31 = gtk_spin_button_new (GTK_ADJUSTMENT (Q_matrix_a31_adj), 1, 0);
  gtk_widget_ref (Q_matrix_a31);
  gtk_object_set_data_full (GTK_OBJECT (window_matrix), "Q_matrix_a31", Q_matrix_a31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_matrix_a31);
  gtk_table_attach (GTK_TABLE (table2), Q_matrix_a31, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_matrix_a31), TRUE);

  gtk_signal_connect (GTK_OBJECT (window_matrix), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_matrix_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a13), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a33), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a23), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a12), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a22), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a32), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a11), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a21), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_matrix_a31), "changed",
                      GTK_SIGNAL_FUNC (on_Q_matrix_changed),
                      NULL);

  return window_matrix;
}

GtkWidget*
create_window_cvector (void)
{
  GtkWidget *window_cvector;
  GtkWidget *vbox11;
  GtkWidget *Q_cvector_reload;
  GtkWidget *Q_colorwheel;

  window_cvector = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_cvector), "window_cvector", window_cvector);
  gtk_window_set_title (GTK_WINDOW (window_cvector), _("window_cvector"));
  gtk_window_set_policy (GTK_WINDOW (window_cvector), TRUE, TRUE, TRUE);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox11);
  gtk_object_set_data_full (GTK_OBJECT (window_cvector), "vbox11", vbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (window_cvector), vbox11);

  Q_cvector_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_cvector_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_cvector), "Q_cvector_reload", Q_cvector_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_cvector_reload);
  gtk_box_pack_start (GTK_BOX (vbox11), Q_cvector_reload, FALSE, FALSE, 0);

  Q_colorwheel = gtk_color_selection_new ();
  gtk_widget_ref (Q_colorwheel);
  gtk_object_set_data_full (GTK_OBJECT (window_cvector), "Q_colorwheel", Q_colorwheel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_colorwheel);
  gtk_box_pack_start (GTK_BOX (vbox11), Q_colorwheel, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (window_cvector), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_cvector_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_cvector_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_colorwheel), "color_changed",
                      GTK_SIGNAL_FUNC (on_Q_colorwheel_color_changed),
                      NULL);

  return window_cvector;
}

GtkWidget*
create_window_toggle (void)
{
  GtkWidget *window_toggle;
  GtkWidget *hbox1;
  GtkWidget *Q_toggle_reload;
  GtkWidget *Q_toggle;

  window_toggle = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_toggle), "window_toggle", window_toggle);
  gtk_window_set_title (GTK_WINDOW (window_toggle), _("window_toggle"));
  gtk_window_set_policy (GTK_WINDOW (window_toggle), TRUE, TRUE, TRUE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (window_toggle), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (window_toggle), hbox1);

  Q_toggle_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_toggle_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_toggle), "Q_toggle_reload", Q_toggle_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_toggle_reload);
  gtk_box_pack_start (GTK_BOX (hbox1), Q_toggle_reload, FALSE, FALSE, 0);

  Q_toggle = gtk_toggle_button_new_with_label (_("0/1"));
  gtk_widget_ref (Q_toggle);
  gtk_object_set_data_full (GTK_OBJECT (window_toggle), "Q_toggle", Q_toggle,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_toggle);
  gtk_box_pack_start (GTK_BOX (hbox1), Q_toggle, TRUE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (window_toggle), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_toggle_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_toggle_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_toggle), "toggled",
                      GTK_SIGNAL_FUNC (on_Q_toggle_toggled),
                      NULL);

  return window_toggle;
}

GtkWidget*
create_window_rect (void)
{
  GtkWidget *window_rect;
  GtkWidget *vbox13;
  GtkWidget *Q_rect_reload;
  GtkWidget *table4;
  GtkObject *Q_rect_h_adj;
  GtkWidget *Q_rect_h;
  GtkObject *Q_rect_w_adj;
  GtkWidget *Q_rect_w;
  GtkObject *Q_rect_y_adj;
  GtkWidget *Q_rect_y;
  GtkObject *Q_rect_x_adj;
  GtkWidget *Q_rect_x;

  window_rect = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_rect), "window_rect", window_rect);
  gtk_window_set_title (GTK_WINDOW (window_rect), _("window_rect"));
  gtk_window_set_policy (GTK_WINDOW (window_rect), TRUE, TRUE, TRUE);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox13);
  gtk_object_set_data_full (GTK_OBJECT (window_rect), "vbox13", vbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (window_rect), vbox13);

  Q_rect_reload = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (Q_rect_reload);
  gtk_object_set_data_full (GTK_OBJECT (window_rect), "Q_rect_reload", Q_rect_reload,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_rect_reload);
  gtk_box_pack_start (GTK_BOX (vbox13), Q_rect_reload, FALSE, FALSE, 0);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (window_rect), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox13), table4, TRUE, TRUE, 0);

  Q_rect_h_adj = gtk_adjustment_new (0, 0, 65535, 1, 256, 256);
  Q_rect_h = gtk_spin_button_new (GTK_ADJUSTMENT (Q_rect_h_adj), 1, 0);
  gtk_widget_ref (Q_rect_h);
  gtk_object_set_data_full (GTK_OBJECT (window_rect), "Q_rect_h", Q_rect_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_rect_h);
  gtk_table_attach (GTK_TABLE (table4), Q_rect_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_rect_h), TRUE);

  Q_rect_w_adj = gtk_adjustment_new (0, 0, 65535, 1, 256, 256);
  Q_rect_w = gtk_spin_button_new (GTK_ADJUSTMENT (Q_rect_w_adj), 1, 0);
  gtk_widget_ref (Q_rect_w);
  gtk_object_set_data_full (GTK_OBJECT (window_rect), "Q_rect_w", Q_rect_w,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_rect_w);
  gtk_table_attach (GTK_TABLE (table4), Q_rect_w, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_rect_w), TRUE);

  Q_rect_y_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_rect_y = gtk_spin_button_new (GTK_ADJUSTMENT (Q_rect_y_adj), 1, 0);
  gtk_widget_ref (Q_rect_y);
  gtk_object_set_data_full (GTK_OBJECT (window_rect), "Q_rect_y", Q_rect_y,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_rect_y);
  gtk_table_attach (GTK_TABLE (table4), Q_rect_y, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_rect_y), TRUE);

  Q_rect_x_adj = gtk_adjustment_new (0, -32768, 32767, 1, 256, 256);
  Q_rect_x = gtk_spin_button_new (GTK_ADJUSTMENT (Q_rect_x_adj), 1, 0);
  gtk_widget_ref (Q_rect_x);
  gtk_object_set_data_full (GTK_OBJECT (window_rect), "Q_rect_x", Q_rect_x,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Q_rect_x);
  gtk_table_attach (GTK_TABLE (table4), Q_rect_x, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (Q_rect_x), TRUE);

  gtk_signal_connect (GTK_OBJECT (Q_rect_reload), "clicked",
                      GTK_SIGNAL_FUNC (on_Q_rect_reload_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_rect_h), "changed",
                      GTK_SIGNAL_FUNC (on_Q_rect_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_rect_w), "changed",
                      GTK_SIGNAL_FUNC (on_Q_rect_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_rect_y), "changed",
                      GTK_SIGNAL_FUNC (on_Q_rect_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Q_rect_x), "changed",
                      GTK_SIGNAL_FUNC (on_Q_rect_changed),
                      NULL);

  return window_rect;
}

