/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_app (void);
GtkWidget* create_about (void);
GtkWidget* create_window_uchar (void);
GtkWidget* create_window_char (void);
GtkWidget* create_window_ushort (void);
GtkWidget* create_window_short (void);
GtkWidget* create_window_long (void);
GtkWidget* create_window_ulong (void);
GtkWidget* create_window_svector (void);
GtkWidget* create_window_vector (void);
GtkWidget* create_window_matrix (void);
GtkWidget* create_window_cvector (void);
GtkWidget* create_window_toggle (void);
GtkWidget* create_window_rect (void);
