/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"

GtkWidget *clist = NULL;
gchar *the_filename = NULL;

void retrieve_symbols (char *filename, GtkCList *list);

int
main (int argc, char *argv[])
{
  GtkWidget *app;

  if (argc!=2) { printf("need a filename as argument\n"); return (1); }
  the_filename = argv[1];
  

  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);

  gnome_init ("interactor", VERSION, argc, argv);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  app = create_app ();
  gtk_widget_show (app);

	clist = lookup_widget(app,"clist");

	retrieve_symbols (the_filename,clist);

  gtk_main ();
  return 0;
}

