/* Automatically generated by po2tbl.sed from timtools.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"be quiet", 2},
  {"print this text", 3},
  {"be verbose", 4},
  {"print binary version", 5},
  {"set output file", 6},
  {"set image type (0=4-bit,1=8-bit,2=15-bit,3=24-bit)", 7},
  {"scale to new width (default: do not scale)", 8},
  {"scale to new height (default: do not scale)", 9},
  {"\
%s - any to tim image converter\n\
Copyright (C) 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 10},
  {"Usage: %s [options] <filename>\n", 11},
  {"%s: input dimension: %dx%d\n", 12},
  {"%s: scaled to: %dx%d\n", 13},
  {"width", 14},
  {"height", 15},
  {"mode (0..3)", 16},
  {"output", 17},
  {"number of cluts", 18},
  {"\
%s - montage of multiple TIM images to one new image\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 19},
  {"input filename missing", 20},
  {"input file has zero length", 21},
  {"clut x", 22},
  {"clut y", 23},
  {"pixel x", 24},
  {"pixel y", 25},
  {"\
%s - set position of TIM contents\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 26},
  {"shift 15-bit to full 24-bit (brighter colors)", 27},
  {"\
%s - RAW BINARY to PS-X EXE converter\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 28},
};

int _msg_tbl_length = 28;
