/* Automatically generated by po2tbl.sed from psxtools.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"be quiet", 2},
  {"print this text", 3},
  {"be verbose", 4},
  {"print binary version", 5},
  {"set output file", 6},
  {"set area code for europe", 7},
  {"set area code for north america", 8},
  {"set area code for japan", 9},
  {"set stack pointer (SP, default: 0x801ffff0)", 10},
  {"use global pointer of object file (GP, default: 0x00000000)", 11},
  {"set a custom area code string", 12},
  {"\
%s - BFD to PS-X EXE converter\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 13},
  {"GP not supported with ELF", 14},
  {"Usage: %s [options] <filename>\n", 15},
  {"input filename missing", 16},
  {"Reading from \"%s\"\n", 17},
  {"Writing to \"%s\"\n", 18},
  {"Object file format is \"%s\"\n", 19},
  {"GP optimized size is %d\n", 20},
  {"Executable not stripped!\n", 21},
  {"Section \"%8s\" is not stripped\n", 22},
  {"Section \"%8s\" will be exported\n", 23},
  {"Aligning: %d -> %d\n", 24},
  {"PC=0x%08lx GP=0x%08lx Base=%08lx Size=0x%08lx\n", 25},
  {"Section [%8s] Address [%08lx] Length [%06lx]", 26},
  {"set base address (default: 0x80010000)", 27},
  {"set program counter (PC, default: address)", 28},
  {"set global pointer (GP, default: 0)", 29},
  {"\
%s - RAW BINARY to PS-X EXE converter\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 30},
  {"Object file format is \"RAW BINARY\"\n", 31},
  {"Section [   .text] Address [%08lx] Length [%06lx] *\n", 32},
  {"use this device (default: /dev/pccl)", 33},
  {"\
%s - download content of code preservation area\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 34},
  {"invalid checksum (%02x/%02x)", 35},
  {"O.K.\n", 36},
  {"\
%s - upload a file to the code preservation area\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 37},
  {"input file has zero length", 38},
  {"size of code preservation area: %d\n", 39},
  {"not enough memory in code preservation area for that file!", 40},
  {"didn't correspond to checksum", 41},
  {"didn't recognize EEPROM", 42},
  {"failed writing to EEPROM", 43},
  {"unknown error code", 44},
  {"set address (default: 0x80010000)", 45},
  {"number of bytes to download (default: 0)", 46},
  {"\
%s - download memory from the PSX\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 47},
  {"size must be greater than zero", 48},
  {"\
%s - dummy skeleton\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 49},
  {"a localized string...\n", 50},
  {"specify icon file(s) (16x16 4-Bit TIM)", 51},
  {"specify memory card title", 52},
  {"\
%s - PS-X EXE to MEXE converter\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 53},
  {"a maximum of three icons is allowed", 54},
  {"file is not a PSX executable", 55},
  {"using builtin icon of tux the penguin\n", 56},
  {"icon %s has zero length", 57},
  {"using \"%s\" as icon #%d\n", 58},
  {"icon %s is not a TIM image", 59},
  {"icon %s is not a 16x16 4-Bit TIM image", 60},
  {"left edge of image area (default: 0)", 61},
  {"top edge of image area (default: 0)", 62},
  {"width of image area (default: 256)", 63},
  {"height of image area (default: 240)", 64},
  {"pixel mode (0:15-bit, 1:24-bit, default:0)", 65},
  {"\
%s - set PSX frame buffer mode\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 66},
  {"emergency mode (you have to boot with a special CD-ROM)", 67},
  {"\
%s - flash a PAR rom image\n\
Copyright (C) 1999 by Andrew Kieschnick <andrewk@mail.utexas.edu>\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 68},
  {"WARNING: FLASH UPDATE - Turn PSX off and hit CTRL-C to abort!\n", 69},
  {"Press RESET on PSX to continue!\n", 70},
  {"Sending update program.\n", 71},
  {"Transfer error!\n", 72},
  {"Sending ROM image.\n", 73},
  {"Update complete.\n", 74},
  {"icon number (1..3)", 75},
  {"\
%s - get icon from memory card image\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 76},
  {"icon number must be between 1 and 3", 77},
  {"file is not a memory card image", 78},
  {"%d icon(s) in %s\n", 79},
  {"only %d icon(s) in %s, using first", 80},
  {"\
%s - get control over the PSX\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 81},
  {"memory card slot (default: 0)", 82},
  {"list in long format", 83},
  {"show sjis encoded file comment", 84},
  {"\
%s - list the contents of a memory card\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 85},
  {"\
%s - download file(s) from a memory card\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 86},
  {"downloading %s\n", 87},
  {"invalid checksum (%04x/%04x)", 88},
  {"force operation (default: ask)", 89},
  {"\
%s - upload file(s) to a memory card\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 90},
  {"uploading %s\n", 91},
  {"delete file \"%s\" [yes/no]? :", 92},
  {"yes", 93},
  {"deleting %s\n", 94},
  {"THIS APPLICATION DOES NOT YET WORK CORRECTLY - USE AT YOUR OWN RISK", 95},
  {"\
%s - configure global modes of a device\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 96},
  {"\
%s - reset the PSX\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 97},
  {"\
%s - give control back to the PSX\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 98},
  {"\
%s - delete a file from a memory card\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 99},
  {"deleting \"%s\"...\n", 100},
  {"number of tasks allowed (default: 4)", 101},
  {"number of events allowed (default: 16)", 102},
  {"initial stack address (default: 0x801ffff0)", 103},
  {"run with full stdio and file server", 104},
  {"run without server, but with console mode activated", 105},
  {"normal start", 106},
  {"reset PSX before upload", 107},
  {"break execution at main() function", 108},
  {"poll until the game stops", 109},
  {"where to place argv/argc arguments in memory", 110},
  {"\
%s - upload and start PS-X EXE files\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 111},
  {"\
%s - stdio and file server for the PSX\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 112},
  {"\
%s - show the contents of the MIPS CPU registers\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 113},
  {"no program is running", 114},
  {"left edge of image area (default: caetla FBV)", 115},
  {"top edge of image area (default: caetla FBV)", 116},
  {"width of image area (default: caetla FBV)", 117},
  {"height of image area (default: caetla FBV)", 118},
  {"\
%s - download a TIM image from the framebuffer\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 119},
  {"Downloading +%d+%d %dx%d (mode %d)\n", 120},
  {"left edge of pixel (default: TIM)", 121},
  {"top edge of pixel (default: TIM)", 122},
  {"left edge of clut (default: TIM)", 123},
  {"top edge of clut (default: TIM)", 124},
  {"\
%s - upload a TIM image to the framebuffer\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 125},
  {"not a TIM image!", 126},
  {"\
%s - upload memory to the PSX\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 127},
  {"\
%s - download XA list\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 128},
  {"\
%s - dump a XA list file\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 129},
  {"file is not a XA-LIST", 130},
  {"Volume: %s\n", 131},
  {"Filename: %s\n", 132},
  {"Audio: %02x:%02x:%02x - %02x:%02x:%02x (Speed:%dX, Interleave:%d)\n", 133},
  {"Movie: %02x:%02x:%02x - %02x:%02x:%02x\n", 134},
  {"\
%s - upload XA list\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 135},
  {"invalid header", 136},
  {"unsupported version", 137},
  {"over size", 138},
  {"inconsistency checksum", 139},
};

int _msg_tbl_length = 139;
