/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_window1 ()
{
  GtkWidget *window1;
  GtkWidget *v2box2;
  GtkWidget *notebook1;
  GtkWidget *label16;
  GtkWidget *label1;
  GtkWidget *vbox2222;
  GtkWidget *vpaned1;
  GtkWidget *vbox2;
  GtkWidget *table4;
  GtkWidget *manpage_title;
  GtkWidget *manpage_description;
  GtkWidget *manpage_author;
  GtkWidget *manpage_seealso;
  GtkWidget *label8;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *manpage_package;
  GtkWidget *Description;
  GtkWidget *scrolledwindow3;
  GtkWidget *manpage_body;
  GtkWidget *Examples;
  GtkWidget *scrolledwindow4;
  GtkWidget *manpage_examples;
  GtkWidget *Bugs;
  GtkWidget *scrolledwindow11;
  GtkWidget *manpage_bugs;
  GtkWidget *Notes;
  GtkWidget *scrolledwindow6;
  GtkWidget *manpage_notes;
  GtkWidget *frame8;
  GtkWidget *scrolledwindow2;
  GtkWidget *manpages;
  GtkWidget *hbuttonbox2;
  guint manpage_add_key;
  GtkWidget *manpage_add;
  guint manpage_delete_key;
  GtkWidget *manpage_delete;
  guint manpage_clear_key;
  GtkWidget *manpage_clear;
  guint manpage_sync_key;
  GtkWidget *manpage_sync;
  GtkWidget *label2;
  GtkWidget *vbox1;
  GtkWidget *vpaned2;
  GtkWidget *vbox2223;
  GtkWidget *table2;
  GtkWidget *title;
  GtkWidget *url;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *author;
  GtkWidget *label4;
  GtkWidget *label17;
  GtkWidget *hbox2;
  GtkWidget *dateedit1;
  GtkWidget *button_get_time_and_date;
  GtkWidget *frame15;
  GtkWidget *scrolledwindow1;
  GtkWidget *body;
  GtkWidget *frame17;
  GtkWidget *scrolledwindow12;
  GtkWidget *viewport1;
  GtkWidget *news;
  GtkWidget *hbuttonbox1;
  guint add_key;
  GtkWidget *add;
  guint clear_key;
  GtkWidget *clear;
  guint news_delete_key;
  GtkWidget *news_delete;
  guint news_sync_key;
  GtkWidget *news_sync;
  GtkWidget *label3;
  GtkWidget *vbox2226;
  GtkWidget *frame23;
  GtkWidget *table6;
  GtkWidget *screenshot_title;
  GtkWidget *label31;
  GtkWidget *frame24;
  GtkWidget *scrolledwindow16;
  GtkWidget *screenshot_comment;
  GtkWidget *vpaned4;
  GtkWidget *frame22;
  GtkWidget *screenshot_image;
  GtkWidget *entry2;
  GtkWidget *screenshot_filename;
  GtkWidget *frame21;
  GtkWidget *scrolledwindow15;
  GtkWidget *viewport2;
  GtkWidget *screenshots;
  GtkWidget *hbuttonbox4;
  guint screenshot_add_key;
  GtkWidget *screenshot_add;
  guint screenshot_clear_key;
  GtkWidget *screenshot_clear;
  guint screenshot_delete_key;
  GtkWidget *screenshot_delete;
  guint screenshot_sync_key;
  GtkWidget *screenshot_sync;
  GtkWidget *label18;
  GtkWidget *empty_notebook_page;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *vbox2224;
  GtkWidget *vpaned3;
  GtkWidget *vbox2225;
  GtkWidget *frame19;
  GtkWidget *table5;
  GtkWidget *faq_question;
  GtkWidget *combo2;
  GList *combo2_items = NULL;
  GtkWidget *faq_category;
  GtkWidget *label26;
  GtkWidget *label25;
  GtkWidget *frame20;
  GtkWidget *scrolledwindow14;
  GtkWidget *faq_answer;
  GtkWidget *frame18;
  GtkWidget *scrolledwindow13;
  GtkWidget *faqs;
  GtkWidget *hbuttonbox3;
  guint faq_add_key;
  GtkWidget *faq_add;
  guint faq_clear_key;
  GtkWidget *faq_clear;
  guint faq_delete_key;
  GtkWidget *faq_delete;
  guint faq_sync_key;
  GtkWidget *faq_sync;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *vbox2227;
  GtkWidget *scrolledwindow17;
  GtkWidget *viewport3;
  GtkWidget *label32;
  GtkWidget *hbuttonbox5;
  guint button16_key;
  GtkWidget *button16;
  GtkWidget *label24;
  GtkWidget *alignment1;
  guint button6_key;
  GtkWidget *button6;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window1), "window1", window1);
  gtk_window_set_title (GTK_WINDOW (window1), _("psxdev.de webtool - Copyright (C) 1999 by Daniel Balster <dbalster@psxdev.de>"));

  v2box2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (v2box2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "v2box2", v2box2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (v2box2);
  gtk_container_add (GTK_CONTAINER (window1), v2box2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (v2box2), notebook1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (notebook1), 8);

  label16 = gtk_label_new (_("psxdev.de webtool\nCopyright (C) 1999 by Daniel Balster <dbalster@psxdev.de>\nAll Rights Reserved."));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (notebook1), label16);

  label1 = gtk_label_new (_("?"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  vbox2222 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2222);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox2222", vbox2222,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2222);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2222);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_box_pack_start (GTK_BOX (vbox2222), vpaned1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 4);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (vpaned1), vbox2);

  table4 = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox2), table4, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 2);

  manpage_title = gtk_entry_new ();
  gtk_widget_ref (manpage_title);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_title", manpage_title,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_title);
  gtk_table_attach (GTK_TABLE (table4), manpage_title, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  manpage_description = gtk_entry_new ();
  gtk_widget_ref (manpage_description);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_description", manpage_description,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_description);
  gtk_table_attach (GTK_TABLE (table4), manpage_description, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  manpage_author = gtk_entry_new ();
  gtk_widget_ref (manpage_author);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_author", manpage_author,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_author);
  gtk_table_attach (GTK_TABLE (table4), manpage_author, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (manpage_author), _("Daniel Balster <dbalster@psxdev.de>"));

  manpage_seealso = gtk_entry_new ();
  gtk_widget_ref (manpage_seealso);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_seealso", manpage_seealso,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_seealso);
  gtk_table_attach (GTK_TABLE (table4), manpage_seealso, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label8 = gtk_label_new (_("Description:"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table4), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 7.45058e-09, 0.5);

  label12 = gtk_label_new (_("Title:"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table4), label12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 7.45058e-09, 0.5);

  label13 = gtk_label_new (_("Author:"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table4), label13, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 7.45058e-09, 0.5);

  label14 = gtk_label_new (_("Package:"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table4), label14, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 7.45058e-09, 0.5);

  label15 = gtk_label_new (_("See Also:"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table4), label15, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 7.45058e-09, 0.5);

  combo1 = gtk_combo_new ();
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_table_attach (GTK_TABLE (table4), combo1, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  combo1_items = g_list_append (combo1_items, _("psxdev-tools"));
  combo1_items = g_list_append (combo1_items, _("psxdev-core"));
  combo1_items = g_list_append (combo1_items, _("psxdev-apps"));
  combo1_items = g_list_append (combo1_items, _("psxdev-libs"));
  combo1_items = g_list_append (combo1_items, _("psxdev-binutils"));
  combo1_items = g_list_append (combo1_items, _("psxdev-media"));
  combo1_items = g_list_append (combo1_items, _("psxdev-egcs"));
  combo1_items = g_list_append (combo1_items, _("psxdev-gcc"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  manpage_package = GTK_COMBO (combo1)->entry;
  gtk_widget_ref (manpage_package);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_package", manpage_package,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_package);
  gtk_entry_set_text (GTK_ENTRY (manpage_package), _("psxdev-tools"));

  Description = gtk_frame_new (_("Description"));
  gtk_widget_ref (Description);
  gtk_object_set_data_full (GTK_OBJECT (window1), "Description", Description,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Description);
  gtk_box_pack_start (GTK_BOX (vbox2), Description, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (Description), GTK_SHADOW_NONE);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (Description), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  manpage_body = gtk_text_new (NULL, NULL);
  gtk_widget_ref (manpage_body);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_body", manpage_body,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_body);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), manpage_body);
  gtk_text_set_editable (GTK_TEXT (manpage_body), TRUE);

  Examples = gtk_frame_new (_("Examples"));
  gtk_widget_ref (Examples);
  gtk_object_set_data_full (GTK_OBJECT (window1), "Examples", Examples,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Examples);
  gtk_box_pack_start (GTK_BOX (vbox2), Examples, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (Examples), GTK_SHADOW_NONE);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (Examples), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  manpage_examples = gtk_text_new (NULL, NULL);
  gtk_widget_ref (manpage_examples);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_examples", manpage_examples,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_examples);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), manpage_examples);
  gtk_text_set_editable (GTK_TEXT (manpage_examples), TRUE);

  Bugs = gtk_frame_new (_("Bugs"));
  gtk_widget_ref (Bugs);
  gtk_object_set_data_full (GTK_OBJECT (window1), "Bugs", Bugs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bugs);
  gtk_box_pack_start (GTK_BOX (vbox2), Bugs, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (Bugs), GTK_SHADOW_NONE);

  scrolledwindow11 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow11);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow11", scrolledwindow11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow11);
  gtk_container_add (GTK_CONTAINER (Bugs), scrolledwindow11);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  manpage_bugs = gtk_text_new (NULL, NULL);
  gtk_widget_ref (manpage_bugs);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_bugs", manpage_bugs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_bugs);
  gtk_container_add (GTK_CONTAINER (scrolledwindow11), manpage_bugs);
  gtk_text_set_editable (GTK_TEXT (manpage_bugs), TRUE);

  Notes = gtk_frame_new (_("Notes"));
  gtk_widget_ref (Notes);
  gtk_object_set_data_full (GTK_OBJECT (window1), "Notes", Notes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Notes);
  gtk_box_pack_start (GTK_BOX (vbox2), Notes, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (Notes), GTK_SHADOW_NONE);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow6", scrolledwindow6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (Notes), scrolledwindow6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  manpage_notes = gtk_text_new (NULL, NULL);
  gtk_widget_ref (manpage_notes);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_notes", manpage_notes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_notes);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), manpage_notes);
  gtk_text_set_editable (GTK_TEXT (manpage_notes), TRUE);

  frame8 = gtk_frame_new (_("Manual Pages"));
  gtk_widget_ref (frame8);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame8", frame8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame8);
  gtk_container_add (GTK_CONTAINER (vpaned1), frame8);
  gtk_frame_set_shadow_type (GTK_FRAME (frame8), GTK_SHADOW_NONE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (frame8), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  manpages = create_filebrowser ("manpages", "psxdev/data/manpages", NULL, 0, 0);
  gtk_widget_ref (manpages);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpages", manpages,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpages);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), manpages);
  GTK_WIDGET_UNSET_FLAGS (manpages, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (manpages, GTK_CAN_DEFAULT);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2222), hbuttonbox2, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox2), 85, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox2), 0, 0);

  manpage_add = gtk_button_new_with_label ("");
  manpage_add_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (manpage_add)->child),
                                   _("_Add"));
  gtk_widget_add_accelerator (manpage_add, "clicked", accel_group,
                              manpage_add_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (manpage_add);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_add", manpage_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_add);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), manpage_add);
  GTK_WIDGET_SET_FLAGS (manpage_add, GTK_CAN_DEFAULT);

  manpage_delete = gtk_button_new_with_label ("");
  manpage_delete_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (manpage_delete)->child),
                                   _("_Delete"));
  gtk_widget_add_accelerator (manpage_delete, "clicked", accel_group,
                              manpage_delete_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (manpage_delete);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_delete", manpage_delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_delete);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), manpage_delete);
  GTK_WIDGET_SET_FLAGS (manpage_delete, GTK_CAN_DEFAULT);

  manpage_clear = gtk_button_new_with_label ("");
  manpage_clear_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (manpage_clear)->child),
                                   _("_Clear"));
  gtk_widget_add_accelerator (manpage_clear, "clicked", accel_group,
                              manpage_clear_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (manpage_clear);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_clear", manpage_clear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_clear);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), manpage_clear);
  GTK_WIDGET_SET_FLAGS (manpage_clear, GTK_CAN_DEFAULT);

  manpage_sync = gtk_button_new_with_label ("");
  manpage_sync_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (manpage_sync)->child),
                                   _("_Sync"));
  gtk_widget_add_accelerator (manpage_sync, "clicked", accel_group,
                              manpage_sync_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (manpage_sync);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manpage_sync", manpage_sync,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage_sync);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), manpage_sync);
  GTK_WIDGET_SET_FLAGS (manpage_sync, GTK_CAN_DEFAULT);

  label2 = gtk_label_new (_("Manpages"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox1);

  vpaned2 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned2", vpaned2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned2);
  gtk_box_pack_start (GTK_BOX (vbox1), vpaned2, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (vpaned2), 0);

  vbox2223 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2223);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox2223", vbox2223,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2223);
  gtk_container_add (GTK_CONTAINER (vpaned2), vbox2223);

  table2 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox2223), table2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 2);

  title = gtk_entry_new ();
  gtk_widget_ref (title);
  gtk_object_set_data_full (GTK_OBJECT (window1), "title", title,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (title);
  gtk_table_attach (GTK_TABLE (table2), title, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  url = gtk_entry_new ();
  gtk_widget_ref (url);
  gtk_object_set_data_full (GTK_OBJECT (window1), "url", url,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (url);
  gtk_table_attach (GTK_TABLE (table2), url, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("Title:"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 7.45058e-09, 0.5);

  label6 = gtk_label_new (_("URL:"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table2), label6, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 7.45058e-09, 0.5);

  author = gtk_entry_new ();
  gtk_widget_ref (author);
  gtk_object_set_data_full (GTK_OBJECT (window1), "author", author,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (author);
  gtk_table_attach (GTK_TABLE (table2), author, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (author), _("Daniel Balster <dbalster@psxdev.de>"));

  label4 = gtk_label_new (_("Author:"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table2), label4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 7.45058e-09, 0.5);

  label17 = gtk_label_new (_("Date:"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table2), label17, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 7.45058e-09, 0.5);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table2), hbox2, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  dateedit1 = gnome_date_edit_new ((time_t) 0, TRUE, TRUE);
  gtk_widget_ref (dateedit1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "dateedit1", dateedit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dateedit1);
  gtk_box_pack_start (GTK_BOX (hbox2), dateedit1, TRUE, TRUE, 0);

  button_get_time_and_date = gtk_button_new_with_label (_("Get Current Time and Date"));
  gtk_widget_ref (button_get_time_and_date);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button_get_time_and_date", button_get_time_and_date,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_get_time_and_date);
  gtk_box_pack_start (GTK_BOX (hbox2), button_get_time_and_date, FALSE, FALSE, 0);

  frame15 = gtk_frame_new (_("Message Body"));
  gtk_widget_ref (frame15);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame15", frame15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame15);
  gtk_box_pack_start (GTK_BOX (vbox2223), frame15, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame15), GTK_SHADOW_NONE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (frame15), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  body = gtk_text_new (NULL, NULL);
  gtk_widget_ref (body);
  gtk_object_set_data_full (GTK_OBJECT (window1), "body", body,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (body);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), body);
  gtk_text_set_editable (GTK_TEXT (body), TRUE);

  frame17 = gtk_frame_new (_("News "));
  gtk_widget_ref (frame17);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame17", frame17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame17);
  gtk_container_add (GTK_CONTAINER (vpaned2), frame17);
  gtk_frame_set_shadow_type (GTK_FRAME (frame17), GTK_SHADOW_NONE);

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow12);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow12", scrolledwindow12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow12);
  gtk_container_add (GTK_CONTAINER (frame17), scrolledwindow12);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow12), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), viewport1);

  news = create_filebrowser ("news", "psxdev/data/news", NULL, 0, 0);
  gtk_widget_ref (news);
  gtk_object_set_data_full (GTK_OBJECT (window1), "news", news,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (news);
  gtk_container_add (GTK_CONTAINER (viewport1), news);
  GTK_WIDGET_UNSET_FLAGS (news, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (news, GTK_CAN_DEFAULT);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox1), 4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox1), 80, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox1), 0, 0);

  add = gtk_button_new_with_label ("");
  add_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (add)->child),
                                   _("_Add"));
  gtk_widget_add_accelerator (add, "clicked", accel_group,
                              add_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (add);
  gtk_object_set_data_full (GTK_OBJECT (window1), "add", add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), add);
  GTK_WIDGET_SET_FLAGS (add, GTK_CAN_DEFAULT);

  clear = gtk_button_new_with_label ("");
  clear_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (clear)->child),
                                   _("_Clear"));
  gtk_widget_add_accelerator (clear, "clicked", accel_group,
                              clear_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (clear);
  gtk_object_set_data_full (GTK_OBJECT (window1), "clear", clear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clear);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), clear);
  GTK_WIDGET_SET_FLAGS (clear, GTK_CAN_DEFAULT);

  news_delete = gtk_button_new_with_label ("");
  news_delete_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (news_delete)->child),
                                   _("_Delete"));
  gtk_widget_add_accelerator (news_delete, "clicked", accel_group,
                              news_delete_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (news_delete);
  gtk_object_set_data_full (GTK_OBJECT (window1), "news_delete", news_delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (news_delete);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), news_delete);
  GTK_WIDGET_SET_FLAGS (news_delete, GTK_CAN_DEFAULT);

  news_sync = gtk_button_new_with_label ("");
  news_sync_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (news_sync)->child),
                                   _("_Sync"));
  gtk_widget_add_accelerator (news_sync, "clicked", accel_group,
                              news_sync_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (news_sync);
  gtk_object_set_data_full (GTK_OBJECT (window1), "news_sync", news_sync,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (news_sync);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), news_sync);
  GTK_WIDGET_SET_FLAGS (news_sync, GTK_CAN_DEFAULT);

  label3 = gtk_label_new (_("News"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  vbox2226 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2226);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox2226", vbox2226,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2226);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2226);

  frame23 = gtk_frame_new (_("Blubber"));
  gtk_widget_ref (frame23);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame23", frame23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame23);
  gtk_box_pack_start (GTK_BOX (vbox2226), frame23, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame23), GTK_SHADOW_NONE);

  table6 = gtk_table_new (1, 2, FALSE);
  gtk_widget_ref (table6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "table6", table6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (frame23), table6);
  gtk_container_set_border_width (GTK_CONTAINER (table6), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table6), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 2);

  screenshot_title = gtk_entry_new ();
  gtk_widget_ref (screenshot_title);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshot_title", screenshot_title,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot_title);
  gtk_table_attach (GTK_TABLE (table6), screenshot_title, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label31 = gtk_label_new (_("Title:"));
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table6), label31, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 7.45058e-09, 0.5);

  frame24 = gtk_frame_new (_("Comment"));
  gtk_widget_ref (frame24);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame24", frame24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame24);
  gtk_box_pack_start (GTK_BOX (vbox2226), frame24, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame24), GTK_SHADOW_NONE);

  scrolledwindow16 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow16);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow16", scrolledwindow16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow16);
  gtk_container_add (GTK_CONTAINER (frame24), scrolledwindow16);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow16), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  screenshot_comment = gtk_text_new (NULL, NULL);
  gtk_widget_ref (screenshot_comment);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshot_comment", screenshot_comment,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot_comment);
  gtk_container_add (GTK_CONTAINER (scrolledwindow16), screenshot_comment);
  gtk_text_set_editable (GTK_TEXT (screenshot_comment), TRUE);

  vpaned4 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned4", vpaned4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned4);
  gtk_box_pack_start (GTK_BOX (vbox2226), vpaned4, TRUE, TRUE, 0);

  frame22 = gtk_frame_new (_("Screenshot Image"));
  gtk_widget_ref (frame22);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame22", frame22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame22);
  gtk_container_add (GTK_CONTAINER (vpaned4), frame22);
  gtk_frame_set_shadow_type (GTK_FRAME (frame22), GTK_SHADOW_NONE);

  screenshot_image = gnome_pixmap_entry_new (NULL, NULL, TRUE);
  gtk_widget_ref (screenshot_image);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshot_image", screenshot_image,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot_image);
  gtk_container_add (GTK_CONTAINER (frame22), screenshot_image);

  entry2 = gnome_pixmap_entry_gnome_file_entry (GNOME_PIXMAP_ENTRY (screenshot_image));
  gtk_widget_ref (entry2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "entry2", entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry2);

  screenshot_filename = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (entry2));
  gtk_widget_ref (screenshot_filename);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshot_filename", screenshot_filename,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot_filename);

  frame21 = gtk_frame_new (_("Screenshots"));
  gtk_widget_ref (frame21);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame21", frame21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame21);
  gtk_container_add (GTK_CONTAINER (vpaned4), frame21);
  gtk_frame_set_shadow_type (GTK_FRAME (frame21), GTK_SHADOW_NONE);

  scrolledwindow15 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow15);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow15", scrolledwindow15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow15);
  gtk_container_add (GTK_CONTAINER (frame21), scrolledwindow15);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow15), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "viewport2", viewport2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow15), viewport2);

  screenshots = create_filebrowser ("screenshots", "psxdev/data/screenshots", NULL, 0, 0);
  gtk_widget_ref (screenshots);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshots", screenshots,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshots);
  gtk_container_add (GTK_CONTAINER (viewport2), screenshots);
  GTK_WIDGET_UNSET_FLAGS (screenshots, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (screenshots, GTK_CAN_DEFAULT);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox2226), hbuttonbox4, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox4), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox4), 85, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox4), 0, 0);

  screenshot_add = gtk_button_new_with_label ("");
  screenshot_add_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (screenshot_add)->child),
                                   _("_Add"));
  gtk_widget_add_accelerator (screenshot_add, "clicked", accel_group,
                              screenshot_add_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (screenshot_add);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshot_add", screenshot_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot_add);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), screenshot_add);
  GTK_WIDGET_SET_FLAGS (screenshot_add, GTK_CAN_DEFAULT);

  screenshot_clear = gtk_button_new_with_label ("");
  screenshot_clear_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (screenshot_clear)->child),
                                   _("_Clear"));
  gtk_widget_add_accelerator (screenshot_clear, "clicked", accel_group,
                              screenshot_clear_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (screenshot_clear);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshot_clear", screenshot_clear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot_clear);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), screenshot_clear);
  GTK_WIDGET_SET_FLAGS (screenshot_clear, GTK_CAN_DEFAULT);

  screenshot_delete = gtk_button_new_with_label ("");
  screenshot_delete_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (screenshot_delete)->child),
                                   _("_Delete"));
  gtk_widget_add_accelerator (screenshot_delete, "clicked", accel_group,
                              screenshot_delete_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (screenshot_delete);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshot_delete", screenshot_delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot_delete);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), screenshot_delete);
  GTK_WIDGET_SET_FLAGS (screenshot_delete, GTK_CAN_DEFAULT);

  screenshot_sync = gtk_button_new_with_label ("");
  screenshot_sync_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (screenshot_sync)->child),
                                   _("_Sync"));
  gtk_widget_add_accelerator (screenshot_sync, "clicked", accel_group,
                              screenshot_sync_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (screenshot_sync);
  gtk_object_set_data_full (GTK_OBJECT (window1), "screenshot_sync", screenshot_sync,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot_sync);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), screenshot_sync);
  GTK_WIDGET_SET_FLAGS (screenshot_sync, GTK_CAN_DEFAULT);

  label18 = gtk_label_new (_("Screenshots"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label18);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label19 = gtk_label_new (_("Demos"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label19);
  gtk_widget_set_sensitive (label19, FALSE);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label20 = gtk_label_new (_("E-Mails"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label20);
  gtk_widget_set_sensitive (label20, FALSE);

  vbox2224 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2224);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox2224", vbox2224,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2224);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2224);

  vpaned3 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned3", vpaned3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned3);
  gtk_box_pack_start (GTK_BOX (vbox2224), vpaned3, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (vpaned3), 150);

  vbox2225 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2225);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox2225", vbox2225,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2225);
  gtk_container_add (GTK_CONTAINER (vpaned3), vbox2225);

  frame19 = gtk_frame_new (_("Question"));
  gtk_widget_ref (frame19);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame19", frame19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame19);
  gtk_box_pack_start (GTK_BOX (vbox2225), frame19, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame19), GTK_SHADOW_NONE);

  table5 = gtk_table_new (2, 2, FALSE);
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (frame19), table5);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 2);

  faq_question = gtk_entry_new ();
  gtk_widget_ref (faq_question);
  gtk_object_set_data_full (GTK_OBJECT (window1), "faq_question", faq_question,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faq_question);
  gtk_table_attach (GTK_TABLE (table5), faq_question, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo2 = gtk_combo_new ();
  gtk_widget_ref (combo2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "combo2", combo2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo2);
  gtk_table_attach (GTK_TABLE (table5), combo2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  combo2_items = g_list_append (combo2_items, _("General"));
  combo2_items = g_list_append (combo2_items, _("Driver"));
  combo2_items = g_list_append (combo2_items, _("PlayStation"));
  combo2_items = g_list_append (combo2_items, _("Legal"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo2), combo2_items);
  g_list_free (combo2_items);

  faq_category = GTK_COMBO (combo2)->entry;
  gtk_widget_ref (faq_category);
  gtk_object_set_data_full (GTK_OBJECT (window1), "faq_category", faq_category,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faq_category);
  gtk_entry_set_text (GTK_ENTRY (faq_category), _("General"));

  label26 = gtk_label_new (_("Category:"));
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table5), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 7.45058e-09, 0.5);

  label25 = gtk_label_new (_("Question:"));
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table5), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 7.45058e-09, 0.5);

  frame20 = gtk_frame_new (_("Answer"));
  gtk_widget_ref (frame20);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame20", frame20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame20);
  gtk_box_pack_start (GTK_BOX (vbox2225), frame20, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame20), GTK_SHADOW_NONE);

  scrolledwindow14 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow14);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow14", scrolledwindow14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow14);
  gtk_container_add (GTK_CONTAINER (frame20), scrolledwindow14);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow14), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  faq_answer = gtk_text_new (NULL, NULL);
  gtk_widget_ref (faq_answer);
  gtk_object_set_data_full (GTK_OBJECT (window1), "faq_answer", faq_answer,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faq_answer);
  gtk_container_add (GTK_CONTAINER (scrolledwindow14), faq_answer);
  gtk_text_set_editable (GTK_TEXT (faq_answer), TRUE);

  frame18 = gtk_frame_new (_("FAQs"));
  gtk_widget_ref (frame18);
  gtk_object_set_data_full (GTK_OBJECT (window1), "frame18", frame18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame18);
  gtk_container_add (GTK_CONTAINER (vpaned3), frame18);
  gtk_frame_set_shadow_type (GTK_FRAME (frame18), GTK_SHADOW_NONE);

  scrolledwindow13 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow13);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow13", scrolledwindow13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow13);
  gtk_container_add (GTK_CONTAINER (frame18), scrolledwindow13);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow13), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  faqs = create_filebrowser ("faqs", "psxdev/data/faqs", NULL, 0, 0);
  gtk_widget_ref (faqs);
  gtk_object_set_data_full (GTK_OBJECT (window1), "faqs", faqs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faqs);
  gtk_container_add (GTK_CONTAINER (scrolledwindow13), faqs);
  GTK_WIDGET_UNSET_FLAGS (faqs, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (faqs, GTK_CAN_DEFAULT);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox2224), hbuttonbox3, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox3), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox3), 85, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox3), 0, 0);

  faq_add = gtk_button_new_with_label ("");
  faq_add_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (faq_add)->child),
                                   _("_Add"));
  gtk_widget_add_accelerator (faq_add, "clicked", accel_group,
                              faq_add_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (faq_add);
  gtk_object_set_data_full (GTK_OBJECT (window1), "faq_add", faq_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faq_add);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), faq_add);
  GTK_WIDGET_SET_FLAGS (faq_add, GTK_CAN_DEFAULT);

  faq_clear = gtk_button_new_with_label ("");
  faq_clear_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (faq_clear)->child),
                                   _("_Clear"));
  gtk_widget_add_accelerator (faq_clear, "clicked", accel_group,
                              faq_clear_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (faq_clear);
  gtk_object_set_data_full (GTK_OBJECT (window1), "faq_clear", faq_clear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faq_clear);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), faq_clear);
  GTK_WIDGET_SET_FLAGS (faq_clear, GTK_CAN_DEFAULT);

  faq_delete = gtk_button_new_with_label ("");
  faq_delete_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (faq_delete)->child),
                                   _("_Delete"));
  gtk_widget_add_accelerator (faq_delete, "clicked", accel_group,
                              faq_delete_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (faq_delete);
  gtk_object_set_data_full (GTK_OBJECT (window1), "faq_delete", faq_delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faq_delete);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), faq_delete);
  GTK_WIDGET_SET_FLAGS (faq_delete, GTK_CAN_DEFAULT);

  faq_sync = gtk_button_new_with_label ("");
  faq_sync_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (faq_sync)->child),
                                   _("_Sync"));
  gtk_widget_add_accelerator (faq_sync, "clicked", accel_group,
                              faq_sync_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (faq_sync);
  gtk_object_set_data_full (GTK_OBJECT (window1), "faq_sync", faq_sync,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (faq_sync);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), faq_sync);
  GTK_WIDGET_SET_FLAGS (faq_sync, GTK_CAN_DEFAULT);

  label21 = gtk_label_new (_("FAQ"));
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 6), label21);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label22 = gtk_label_new (_("Bugreports"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 7), label22);
  gtk_widget_set_sensitive (label22, FALSE);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label23 = gtk_label_new (_("Network Control"));
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 8), label23);
  gtk_widget_set_sensitive (label23, FALSE);

  vbox2227 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2227);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox2227", vbox2227,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2227);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2227);

  scrolledwindow17 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow17);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow17", scrolledwindow17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow17);
  gtk_box_pack_start (GTK_BOX (vbox2227), scrolledwindow17, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow17), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "viewport3", viewport3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow17), viewport3);

  label32 = gtk_label_new ("");
  gtk_label_parse_uline (GTK_LABEL (label32),
                         _("The webpage is currently generated by a perl script.\nClick on the _Make Button to start the generation.\n\nClick on the _Upload Button to publish it into the World Wide Web."));
  gtk_widget_ref (label32);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label32", label32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label32);
  gtk_container_add (GTK_CONTAINER (viewport3), label32);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbuttonbox5", hbuttonbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (vbox2227), hbuttonbox5, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox5), GTK_BUTTONBOX_END);

  button16 = gtk_button_new_with_label ("");
  button16_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (button16)->child),
                                   _("_Make"));
  gtk_widget_add_accelerator (button16, "clicked", accel_group,
                              button16_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (button16);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button16", button16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button16);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  label24 = gtk_label_new (_("Webpage Generation"));
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 9), label24);
  gtk_widget_set_sensitive (label24, FALSE);

  alignment1 = gtk_alignment_new (1, 0.5, 0.1, 1);
  gtk_widget_ref (alignment1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "alignment1", alignment1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (alignment1);
  gtk_box_pack_start (GTK_BOX (v2box2), alignment1, FALSE, FALSE, 0);

  button6 = gtk_button_new_with_label ("");
  button6_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (button6)->child),
                                   _("_Quit"));
  gtk_widget_add_accelerator (button6, "clicked", accel_group,
                              button6_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (alignment1), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (window1), "delete_event",
                      GTK_SIGNAL_FUNC (on_window1_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manpages), "clicked",
                      GTK_SIGNAL_FUNC (on_manpage_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manpage_add), "clicked",
                      GTK_SIGNAL_FUNC (on_manpage_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manpage_delete), "clicked",
                      GTK_SIGNAL_FUNC (on_manpage_delete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manpage_clear), "clicked",
                      GTK_SIGNAL_FUNC (on_manpage_clear_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manpage_sync), "clicked",
                      GTK_SIGNAL_FUNC (on_manpage_sync_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_get_time_and_date), "clicked",
                      GTK_SIGNAL_FUNC (on_button_get_time_and_date_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (news), "clicked",
                      GTK_SIGNAL_FUNC (on_news_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (add), "clicked",
                      GTK_SIGNAL_FUNC (on_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clear), "clicked",
                      GTK_SIGNAL_FUNC (on_clear_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (news_delete), "clicked",
                      GTK_SIGNAL_FUNC (on_news_delete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (news_sync), "clicked",
                      GTK_SIGNAL_FUNC (on_news_sync_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (screenshots), "clicked",
                      GTK_SIGNAL_FUNC (on_screenshot_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (screenshot_add), "clicked",
                      GTK_SIGNAL_FUNC (on_screenshot_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (screenshot_clear), "clicked",
                      GTK_SIGNAL_FUNC (on_screenshot_clear_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (screenshot_delete), "clicked",
                      GTK_SIGNAL_FUNC (on_screenshot_delete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (screenshot_sync), "clicked",
                      GTK_SIGNAL_FUNC (on_screenshot_sync_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (faqs), "clicked",
                      GTK_SIGNAL_FUNC (on_faq_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (faq_add), "clicked",
                      GTK_SIGNAL_FUNC (on_faq_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (faq_clear), "clicked",
                      GTK_SIGNAL_FUNC (on_faq_clear_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (faq_delete), "clicked",
                      GTK_SIGNAL_FUNC (on_faq_delete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (faq_sync), "clicked",
                      GTK_SIGNAL_FUNC (on_faq_sync_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (on_quit_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

