/* Automatically generated by po2tbl.sed from bstools.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"be quiet", 2},
  {"print this text", 3},
  {"be verbose", 4},
  {"print binary version", 5},
  {"set output file", 6},
  {"width of input image (required!)", 7},
  {"height of input image (required!)", 8},
  {"\
%s - BS to PPM image converter\n\
Copyright (C) 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 9},
  {"Usage: %s [options] <filename>\n", 10},
  {"you must specify both, witdh and height!", 11},
  {"set Q scaling factor (default: 1)", 12},
  {"set image type (default: 2)", 13},
  {"scale to new width (default: do not scale)", 14},
  {"scale to new height (default: do not scale)", 15},
  {"limit output size to X bytes (default: do not limit)", 16},
  {"\
%s - any to bs image converter\n\
Copyright (C) 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 17},
  {"%s: input dimension: %dx%d\n", 18},
  {"%s: scaled to: %dx%d\n", 19},
  {"%s: output size: %d bytes\n", 20},
  {"%s: Q scale factor: %d\n", 21},
};

int _msg_tbl_length = 21;
