/* Automatically generated by po2tbl.sed from psxinteractor.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"_Revert", 2},
  {"PSXDEV Interactor", 3},
  {"Revert", 4},
  {"Open File", 5},
  {"Resume", 6},
  {"Clear Selection", 7},
  {"Halt", 8},
  {"Reset", 9},
  {"Address", 10},
  {"Type", 11},
  {"Variable Name", 12},
  {"CHAR", 13},
  {"UCHAR", 14},
  {"SHORT", 15},
  {"USHORT", 16},
  {"LONG", 17},
  {"ULONG", 18},
  {"SVECTOR", 19},
  {"VECTOR", 20},
  {"MATRIX", 21},
  {"CVECTOR", 22},
  {"RECT", 23},
  {"0/1 Toggle", 24},
  {"Copyright (C) 1999 by Daniel Balster", 25},
  {"Modify data types on a remote target in realtime", 26},
  {"window_uchar", 27},
  {"Reload", 28},
  {"window_char", 29},
  {"window_ushort", 30},
  {"window_short", 31},
  {"window_long", 32},
  {"window_ulong", 33},
  {"window_svector", 34},
  {"window_vector", 35},
  {"window_matrix", 36},
  {"window_cvector", 37},
  {"window_toggle", 38},
  {"0/1", 39},
  {"window_rect", 40},
  {"Couldn't find pixmap file: %s", 41},
  {"Couldn't create pixmap from file: %s", 42},
};

int _msg_tbl_length = 42;
