/* Automatically generated by po2tbl.sed from psx-webtool.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
psxdev.de webtool - Copyright (C) 1999 by Daniel Balster <dbalster@psxdev.de>", 2},
  {"\
psxdev.de webtool\n\
Copyright (C) 1999 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.", 3},
  {"?", 4},
  {"Daniel Balster <dbalster@psxdev.de>", 5},
  {"Description:", 6},
  {"Title:", 7},
  {"Author:", 8},
  {"Package:", 9},
  {"See Also:", 10},
  {"psxdev-tools", 11},
  {"psxdev-core", 12},
  {"psxdev-apps", 13},
  {"psxdev-libs", 14},
  {"psxdev-binutils", 15},
  {"psxdev-media", 16},
  {"psxdev-egcs", 17},
  {"psxdev-gcc", 18},
  {"Description", 19},
  {"Examples", 20},
  {"Bugs", 21},
  {"Notes", 22},
  {"Manual Pages", 23},
  {"_Add", 24},
  {"_Delete", 25},
  {"_Clear", 26},
  {"_Sync", 27},
  {"Manpages", 28},
  {"URL:", 29},
  {"Date:", 30},
  {"Get Current Time and Date", 31},
  {"Message Body", 32},
  {"News ", 33},
  {"News", 34},
  {"Blubber", 35},
  {"Comment", 36},
  {"Screenshot Image", 37},
  {"Screenshots", 38},
  {"Demos", 39},
  {"E-Mails", 40},
  {"Question", 41},
  {"General", 42},
  {"Driver", 43},
  {"PlayStation", 44},
  {"Legal", 45},
  {"Category:", 46},
  {"Question:", 47},
  {"Answer", 48},
  {"FAQs", 49},
  {"FAQ", 50},
  {"Bugreports", 51},
  {"Network Control", 52},
  {"\
The webpage is currently generated by a perl script.\n\
Click on the _Make Button to start the generation.\n\
\n\
Click on the _Upload Button to publish it into the World Wide Web.", 53},
  {"_Make", 54},
  {"Webpage Generation", 55},
  {"_Quit", 56},
  {"Couldn't find pixmap file: %s", 57},
  {"Couldn't create pixmap from file: %s", 58},
};

int _msg_tbl_length = 58;
