/* Automatically generated by po2tbl.sed from pcmtools.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"be quiet", 2},
  {"print this text", 3},
  {"be verbose", 4},
  {"print binary version", 5},
  {"set output file", 6},
  {"\
%s - ADPCM to PCM packer\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
based on VAG-Depacker, hacked by bITmASTER@bigfoot.com\n\
All Rights Reserved.\n\
\n", 7},
  {"Usage: %s [options] <filename>\n", 8},
  {"\
%s - PCM to ADPCM packer\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
based on VAG-Packer, hacked by bITmASTER@bigfoot.com\n\
All Rights Reserved.\n\
\n", 9},
  {"which audio device (default: /dev/dsp)", 10},
  {"enable stereo", 11},
  {"enable mono", 12},
  {"set speed (default: 44100)", 13},
  {"set audio format (default: system default)", 14},
  {"buffer size (default: 4096 bytes)", 15},
  {"set number of channels (default: 1)", 16},
  {"\
%s - play digital audio with OSS\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 17},
  {"unsupported format \"%s\"", 18},
  {"\
%s - query capabilities of OSS compatible audio device\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 19},
  {"%s has the following capabilities:\n", 20},
  {"- Full duplex record/playback\n", 21},
  {"- Real time capability\n", 22},
  {"\
- Device has some kind of internal buffers which may cause some delays and \
decrease precision of timing\n", 23},
  {"- Has a coprocessor (Sometimes it's a DSP but usually not)\n", 24},
  {"- Supports SETTRIGGER\n", 25},
  {"- Supports mmap()\n", 26},
  {"%s supports 0x%08lx: ", 27},
  {"set length (default: 0 bytes)", 28},
  {"set time (default: 1 second)", 29},
  {"use RIFF-WAVE file format (default: raw pcm)", 30},
  {"\
%s - record digital audio with OSS\n\
Copyright (C) 1997, 1998, 1999, 2000 by Daniel Balster <dbalster@psxdev.de>\n\
All Rights Reserved.\n\
\n", 31},
};

int _msg_tbl_length = 31;
