/* Automatically generated by po2tbl.sed from libpsxdev.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Copyright (C) 2000 by Daniel Balster <dbalster@psxdev.de>", 2},
};

int _msg_tbl_length = 2;
