/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("PSXDEV Interactor");
gchar *s = N_("_Revert");
gchar *s = N_("Open File");
gchar *s = N_("Revert");
gchar *s = N_("Clear Selection");
gchar *s = N_("Resume");
gchar *s = N_("Halt");
gchar *s = N_("Reset");
gchar *s = N_("Address");
gchar *s = N_("Type");
gchar *s = N_("Variable Name");
gchar *s = N_("CHAR");
gchar *s = N_("UCHAR");
gchar *s = N_("SHORT");
gchar *s = N_("USHORT");
gchar *s = N_("LONG");
gchar *s = N_("ULONG");
gchar *s = N_("SVECTOR");
gchar *s = N_("VECTOR");
gchar *s = N_("MATRIX");
gchar *s = N_("CVECTOR");
gchar *s = N_("RECT");
gchar *s = N_("0/1 Toggle");
gchar *s = N_("Copyright (C) 1999 by Daniel Balster");
gchar *s = N_("Modify data types on a remote target in realtime");
gchar *s = N_("window_uchar");
gchar *s = N_("Reload");
gchar *s = N_("window_char");
gchar *s = N_("Reload");
gchar *s = N_("window_ushort");
gchar *s = N_("Reload");
gchar *s = N_("window_short");
gchar *s = N_("Reload");
gchar *s = N_("window_long");
gchar *s = N_("Reload");
gchar *s = N_("window_ulong");
gchar *s = N_("Reload");
gchar *s = N_("window_svector");
gchar *s = N_("Reload");
gchar *s = N_("window_vector");
gchar *s = N_("Reload");
gchar *s = N_("window_matrix");
gchar *s = N_("Reload");
gchar *s = N_("window_cvector");
gchar *s = N_("Reload");
gchar *s = N_("window_toggle");
gchar *s = N_("Reload");
gchar *s = N_("0/1");
gchar *s = N_("window_rect");
gchar *s = N_("Reload");
